# Generated by Django 5.2 on 2025-10-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('avg_value', models.FloatField(blank=True, null=True)),
                ('sum_value', models.FloatField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '일별 데이터',
                'verbose_name_plural': '일별 데이터',
                'db_table': 'data_daily',
                'indexes': [models.Index(fields=['timestamp', 'device_id'], name='data_daily_timesta_03adf1_idx')],
                'unique_together': {('timestamp', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='HourlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('avg_value', models.FloatField(blank=True, null=True)),
                ('sum_value', models.FloatField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '1시간 데이터',
                'verbose_name_plural': '1시간 데이터',
                'db_table': 'data_1hour',
                'indexes': [models.Index(fields=['timestamp', 'device_id'], name='data_1hour_timesta_fae18e_idx')],
                'unique_together': {('timestamp', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='TenMinuteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('avg_value', models.FloatField(blank=True, null=True)),
                ('sum_value', models.FloatField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '10분 데이터',
                'verbose_name_plural': '10분 데이터',
                'db_table': 'data_10min',
                'indexes': [models.Index(fields=['timestamp', 'device_id'], name='data_10min_timesta_3e65e0_idx')],
                'unique_together': {('timestamp', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='TwoMinuteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('avg_value', models.FloatField(blank=True, null=True)),
                ('sum_value', models.FloatField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '2분 데이터',
                'verbose_name_plural': '2분 데이터',
                'db_table': 'data_2min',
                'indexes': [models.Index(fields=['timestamp', 'device_id'], name='data_2min_timesta_ef6881_idx')],
                'unique_together': {('timestamp', 'device_id')},
            },
        ),
    ]
