# Generated by Django 5.2 on 2025-10-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailydata',
            name='data_daily_timesta_03adf1_idx',
        ),
        migrations.RemoveIndex(
            model_name='hourlydata',
            name='data_1hour_timesta_fae18e_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenminutedata',
            name='data_10min_timesta_3e65e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='twominutedata',
            name='data_2min_timesta_ef6881_idx',
        ),
        # Add new fields first so subsequent unique/index changes can reference them
        migrations.AddField(
            model_name='dailydata',
            name='client_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='클라이언트를 찾기 위한 id 값', verbose_name='클라이언트 ID'),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='group_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='메모리그룹을 찾기 위한 id 값', verbose_name='메모리그룹 ID'),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='var_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='변수를 찾기 위한 id 값', verbose_name='변수 ID'),
        ),
        migrations.AddField(
            model_name='hourlydata',
            name='client_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='클라이언트를 찾기 위한 id 값', verbose_name='클라이언트 ID'),
        ),
        migrations.AddField(
            model_name='hourlydata',
            name='group_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='메모리그룹을 찾기 위한 id 값', verbose_name='메모리그룹 ID'),
        ),
        migrations.AddField(
            model_name='hourlydata',
            name='var_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='변수를 찾기 위한 id 값', verbose_name='변수 ID'),
        ),
        migrations.AddField(
            model_name='tenminutedata',
            name='client_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='클라이언트를 찾기 위한 id 값', verbose_name='클라이언트 ID'),
        ),
        migrations.AddField(
            model_name='tenminutedata',
            name='group_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='메모리그룹을 찾기 위한 id 값', verbose_name='메모리그룹 ID'),
        ),
        migrations.AddField(
            model_name='tenminutedata',
            name='var_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='변수를 찾기 위한 id 값', verbose_name='변수 ID'),
        ),
        migrations.AddField(
            model_name='twominutedata',
            name='client_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='클라이언트를 찾기 위한 id 값', verbose_name='클라이언트 ID'),
        ),
        migrations.AddField(
            model_name='twominutedata',
            name='group_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='메모리그룹을 찾기 위한 id 값', verbose_name='메모리그룹 ID'),
        ),
        migrations.AddField(
            model_name='twominutedata',
            name='var_id',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='변수를 찾기 위한 id 값', verbose_name='변수 ID'),
        ),
        migrations.AlterUniqueTogether(
            name='dailydata',
            unique_together={('timestamp', 'var_id')},
        ),
        migrations.AlterUniqueTogether(
            name='hourlydata',
            unique_together={('timestamp', 'var_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tenminutedata',
            unique_together={('timestamp', 'var_id')},
        ),
        migrations.AlterUniqueTogether(
            name='twominutedata',
            unique_together={('timestamp', 'var_id')},
        ),
        migrations.AddIndex(
            model_name='dailydata',
            index=models.Index(fields=['timestamp', 'var_id'], name='data_daily_timesta_998c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlydata',
            index=models.Index(fields=['timestamp', 'var_id'], name='data_1hour_timesta_ed1444_idx'),
        ),
        migrations.AddIndex(
            model_name='tenminutedata',
            index=models.Index(fields=['timestamp', 'var_id'], name='data_10min_timesta_351467_idx'),
        ),
        migrations.AddIndex(
            model_name='twominutedata',
            index=models.Index(fields=['timestamp', 'var_id'], name='data_2min_timesta_e7cb72_idx'),
        ),
        migrations.RemoveField(
            model_name='dailydata',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='hourlydata',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='tenminutedata',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='twominutedata',
            name='device_id',
        ),
    ]
