# Generated by Django 5.2 on 2025-10-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_remove_dailydata_data_daily_timesta_03adf1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='client_id',
            field=models.PositiveIntegerField(db_index=True, help_text='클라이언트를 찾기 위한 id 값', verbose_name='클라이언트 ID'),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='group_id',
            field=models.PositiveIntegerField(db_index=True, help_text='메모리그룹을 찾기 위한 id 값', verbose_name='메모리그룹 ID'),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='var_id',
            field=models.PositiveIntegerField(db_index=True, help_text='변수를 찾기 위한 id 값', verbose_name='변수 ID'),
        ),
        migrations.AlterField(
            model_name='hourlydata',
            name='client_id',
            field=models.PositiveIntegerField(db_index=True, help_text='클라이언트를 찾기 위한 id 값', verbose_name='클라이언트 ID'),
        ),
        migrations.AlterField(
            model_name='hourlydata',
            name='group_id',
            field=models.PositiveIntegerField(db_index=True, help_text='메모리그룹을 찾기 위한 id 값', verbose_name='메모리그룹 ID'),
        ),
        migrations.AlterField(
            model_name='hourlydata',
            name='var_id',
            field=models.PositiveIntegerField(db_index=True, help_text='변수를 찾기 위한 id 값', verbose_name='변수 ID'),
        ),
        migrations.AlterField(
            model_name='tenminutedata',
            name='client_id',
            field=models.PositiveIntegerField(db_index=True, help_text='클라이언트를 찾기 위한 id 값', verbose_name='클라이언트 ID'),
        ),
        migrations.AlterField(
            model_name='tenminutedata',
            name='group_id',
            field=models.PositiveIntegerField(db_index=True, help_text='메모리그룹을 찾기 위한 id 값', verbose_name='메모리그룹 ID'),
        ),
        migrations.AlterField(
            model_name='tenminutedata',
            name='var_id',
            field=models.PositiveIntegerField(db_index=True, help_text='변수를 찾기 위한 id 값', verbose_name='변수 ID'),
        ),
        migrations.AlterField(
            model_name='twominutedata',
            name='client_id',
            field=models.PositiveIntegerField(db_index=True, help_text='클라이언트를 찾기 위한 id 값', verbose_name='클라이언트 ID'),
        ),
        migrations.AlterField(
            model_name='twominutedata',
            name='group_id',
            field=models.PositiveIntegerField(db_index=True, help_text='메모리그룹을 찾기 위한 id 값', verbose_name='메모리그룹 ID'),
        ),
        migrations.AlterField(
            model_name='twominutedata',
            name='var_id',
            field=models.PositiveIntegerField(db_index=True, help_text='변수를 찾기 위한 id 값', verbose_name='변수 ID'),
        ),
    ]
