# Generated by Django 5.2 on 2025-10-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_alter_dailydata_client_id_alter_dailydata_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='value_type',
            field=models.CharField(blank=True, help_text='값 자료형(int,float,bool,str 등)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hourlydata',
            name='value_type',
            field=models.CharField(blank=True, help_text='값 자료형(int,float,bool,str 등)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenminutedata',
            name='value_type',
            field=models.CharField(blank=True, help_text='값 자료형(int,float,bool,str 등)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='twominutedata',
            name='value_type',
            field=models.CharField(blank=True, help_text='값 자료형(int,float,bool,str 등)', max_length=20, null=True),
        ),
    ]
