# Generated by Django 5.2 on 2025-07-08 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='어댑터 이름', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='설명', null=True)),
                ('protocol', models.CharField(help_text='프로토콜 종류 (예: TCP, MQTT, HTTP 등)', max_length=50)),
                ('config', models.JSONField(blank=True, help_text='어댑터별 추가 설정값', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
            ],
        ),
        migrations.CreateModel(
            name='SocketClientConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('host', models.CharField(blank=True, help_text='클라이언트 IP', max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, help_text='클라이언트 포트', null=True)),
                ('blocks', models.JSONField(blank=True, help_text='[{"count": 700, "memory": "%MB", "address": "0", "func_name": "continuous_read_bytes"}]', null=True)),
                ('cron', models.JSONField(blank=True, help_text='cron 설정값', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_used', models.BooleanField(default=True, help_text='사용 여부')),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('zone_style', models.JSONField(blank=True, help_text='존 스타일 정보', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocketClientCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=40, null=True, verbose_name='보낸 유저')),
                ('command', models.CharField(help_text='제어항목 또는 명령 이름', max_length=100)),
                ('value', models.CharField(blank=True, help_text='제어값', max_length=255, null=True)),
                ('control_time', models.DateTimeField(auto_now_add=True, verbose_name='제어시각')),
                ('payload', models.JSONField(blank=True, help_text='보낸 명령의 상세 데이터(바이트 등)', null=True)),
                ('response', models.JSONField(blank=True, help_text='기기로부터 받은 응답(있다면)', null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_logs', to='LSISsocket.socketclientconfig')),
            ],
        ),
        migrations.CreateModel(
            name='SensorNodeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip', models.CharField(blank=True, help_text='센서노드 IP', max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, help_text='센서노드 포트', null=True)),
                ('sensor_type', models.CharField(blank=True, help_text='센서 타입', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('adapter', models.ForeignKey(blank=True, help_text='데이터 읽기/쓰기 어댑터(프로토콜) 선택', null=True, on_delete=django.db.models.deletion.SET_NULL, to='LSISsocket.adapter')),
                ('gateway', models.ForeignKey(blank=True, help_text='게이트웨이 노드(없으면 단독형)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_nodes', to='LSISsocket.socketclientconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ControlNodeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip', models.CharField(blank=True, help_text='제어노드 IP', max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, help_text='제어노드 포트', null=True)),
                ('control_type', models.CharField(blank=True, help_text='제어 타입', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('gateway', models.ForeignKey(blank=True, help_text='게이트웨이 노드(없으면 단독형)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_nodes', to='LSISsocket.socketclientconfig')),
            ],
        ),
        migrations.CreateModel(
            name='SocketClientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailedStatus', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='LSISsocket.socketclientconfig')),
            ],
        ),
        migrations.CreateModel(
            name='SocketClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detailedStatus', models.JSONField(blank=True, null=True)),
                ('error_code', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('values', models.JSONField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='LSISsocket.socketclientconfig')),
            ],
        ),
    ]
