# Generated by Django 5.2 on 2025-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socketclientconfig',
            name='clients',
        ),
        migrations.AddField(
            model_name='socketclientconfig',
            name='blocks',
            field=models.JSONField(blank=True, help_text='block 리스트', null=True),
        ),
        migrations.AddField(
            model_name='socketclientconfig',
            name='host',
            field=models.CharField(blank=True, help_text='클라이언트 호스트 IP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socketclientconfig',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AddField(
            model_name='socketclientconfig',
            name='is_used',
            field=models.BooleanField(default=True, help_text='사용 여부'),
        ),
        migrations.AddField(
            model_name='socketclientconfig',
            name='port',
            field=models.IntegerField(blank=True, help_text='클라이언트 포트', null=True),
        ),
        migrations.AlterField(
            model_name='socketclientconfig',
            name='cron',
            field=models.CharField(blank=True, help_text='cron 설정값', max_length=100, null=True),
        ),
    ]
