# Generated by Django 5.2 on 2025-09-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0001_initial'),
        ('corecode', '0010_alter_deviceinstance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Memory Group',
                'verbose_name_plural': 'Memory Groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('corecode.memorygroup',),
        ),
    ]
