# Generated by Django 5.2 on 2025-04-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0002_remove_socketclientconfig_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socketclientconfig',
            name='host',
            field=models.CharField(blank=True, help_text='[{"count": 700, "memory": "%MB", "address": "0", "func_name": "continuous_read_bytes"}]', max_length=100, null=True),
        ),
    ]
