# Generated by Django 5.2 on 2025-09-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0002_memorygroup'),
        ('corecode', '0011_adapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensornodeconfig',
            name='adapter',
            field=models.ForeignKey(blank=True, help_text='데이터 읽기/쓰기 어댑터(프로토콜) 선택', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.adapter'),
        ),
        migrations.DeleteModel(
            name='Adapter',
        ),
    ]
