# Generated by Django 5.2 on 2025-09-30 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0003_alter_sensornodeconfig_adapter_delete_adapter'),
        ('corecode', '0014_memorygroup_adapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemoryGroup',
        ),
        migrations.CreateModel(
            name='MemoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('size_byte', models.PositiveIntegerField()),
                ('Adapter', models.ForeignKey(blank=True, help_text='이 그룹이 속한 어댑터', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsissocket_memory_groups', to='corecode.adapter')),
                ('Device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsissocket_memory_groups', to='corecode.device')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=2)),
                ('address', models.FloatField()),
                ('data_type', models.CharField(choices=[('bool', 'bool'), ('sint', 'sint'), ('usint', 'usint'), ('int', 'int'), ('uint', 'uint'), ('dint', 'dint'), ('udint', 'udint'), ('float', 'float')], max_length=10)),
                ('unit', models.CharField(choices=[('bit', 'bit'), ('byte', 'byte'), ('word', 'word'), ('dword', 'dword')], max_length=10)),
                ('scale', models.FloatField(default=1)),
                ('offset', models.FloatField(default=0)),
                ('attributes', models.JSONField(blank=True, default=list, help_text="['감시','제어','기록','경보'] 중 복수 선택")),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsissocket_physical_variables', to='corecode.dataname')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='LSISsocket.memorygroup')),
            ],
        ),
    ]
