# Generated by Django 5.2 on 2025-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0003_alter_socketclientconfig_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socketclientconfig',
            name='blocks',
            field=models.JSONField(blank=True, help_text='[{"count": 700, "memory": "%MB", "address": "0", "func_name": "continuous_read_bytes"}]', null=True),
        ),
        migrations.AlterField(
            model_name='socketclientconfig',
            name='host',
            field=models.CharField(blank=True, help_text='클라이언트 IP', max_length=100, null=True),
        ),
    ]
