# Generated by Django 5.2 on 2025-04-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0004_alter_socketclientconfig_blocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socketclientconfig',
            name='cron',
            field=models.JSONField(blank=True, help_text='cron 설정값', null=True),
        ),
    ]
