# Generated by Django 5.2 on 2025-04-29 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0005_alter_socketclientconfig_cron'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketclientlog',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.CreateModel(
            name='SocketClientCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=40, null=True, verbose_name='보낸 유저')),
                ('command', models.CharField(help_text='제어항목 또는 명령 이름', max_length=100)),
                ('value', models.CharField(blank=True, help_text='제어값', max_length=255, null=True)),
                ('control_time', models.DateTimeField(auto_now_add=True, verbose_name='제어시각')),
                ('payload', models.JSONField(blank=True, help_text='보낸 명령의 상세 데이터(바이트 등)', null=True)),
                ('response', models.JSONField(blank=True, help_text='기기로부터 받은 응답(있다면)', null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_logs', to='LSISsocket.socketclientconfig')),
            ],
        ),
    ]
