# Generated by Django 5.2 on 2025-10-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0005_copy_core_memorygroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygroup',
            name='start_address',
            field=models.FloatField(default=0, help_text='메모리 그룹의 시작 주소'),
        ),
        migrations.AddField(
            model_name='variable',
            name='use_group_base_address',
            field=models.BooleanField(default=False, help_text='이 변수의 주소가 그룹의 start_address 기준인지 여부'),
        ),
    ]
