# Generated by Django 5.2 on 2025-10-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0006_memorygroup_start_address_and_more'),
        ('agriseed', '0056_remove_module_calc_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketclientconfig',
            name='calc_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 계산 그룹', related_name='lsissocket_calc_groups', to='agriseed.calcgroup'),
        ),
        migrations.AddField(
            model_name='socketclientconfig',
            name='control_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 제어 그룹', related_name='lsissocket_control_groups', to='agriseed.controlgroup'),
        ),
    ]
