# Generated by Django 5.2 on 2025-04-29 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0006_socketclientlog_is_deleted_socketclientcommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlNodeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip', models.CharField(blank=True, help_text='제어노드 IP', max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, help_text='제어노드 포트', null=True)),
                ('control_type', models.CharField(blank=True, help_text='제어 타입', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('gateway', models.ForeignKey(blank=True, help_text='게이트웨이 노드(없으면 단독형)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_nodes', to='LSISsocket.socketclientconfig')),
            ],
        ),
        migrations.CreateModel(
            name='SensorNodeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip', models.CharField(blank=True, help_text='센서노드 IP', max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, help_text='센서노드 포트', null=True)),
                ('sensor_type', models.CharField(blank=True, help_text='센서 타입', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('gateway', models.ForeignKey(blank=True, help_text='게이트웨이 노드(없으면 단독형)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_nodes', to='LSISsocket.socketclientconfig')),
            ],
        ),
    ]
