# Generated by Django 5.2 on 2025-04-29 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0007_controlnodeconfig_sensornodeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='어댑터 이름', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='설명', null=True)),
                ('protocol', models.CharField(help_text='프로토콜 종류 (예: TCP, MQTT, HTTP 등)', max_length=50)),
                ('config', models.JSONField(blank=True, help_text='어댑터별 추가 설정값', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
            ],
        ),
        migrations.AddField(
            model_name='socketclientconfig',
            name='zone_style',
            field=models.JSONField(blank=True, help_text='존 스타일 정보', null=True),
        ),
        migrations.AddField(
            model_name='sensornodeconfig',
            name='adapter',
            field=models.ForeignKey(blank=True, help_text='데이터 읽기/쓰기 어댑터(프로토콜) 선택', null=True, on_delete=django.db.models.deletion.SET_NULL, to='LSISsocket.adapter'),
        ),
    ]
