# Generated by Django 5.2 on 2025-10-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0007_socketclientconfig_calc_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketclientconfig',
            name='memory_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 메모리 그룹', related_name='lsissocket_memory_groups', to='LSISsocket.memorygroup'),
        ),
        migrations.AlterField(
            model_name='socketclientconfig',
            name='blocks',
            field=models.JSONField(blank=True, help_text='[{"address":"0","id":1,"count":700,"func_name":"continuous_read_bytes","memory":"%MB"},{"address":"700","id":2,"count":700,"func_name":"continuous_read_bytes","memory":"%MB"}]', null=True),
        ),
    ]
