# Generated by Django 5.2 on 2025-05-01 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0008_adapter_socketclientconfig_zone_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socketclientconfig',
            name='comm_at',
        ),
        migrations.RemoveField(
            model_name='socketclientconfig',
            name='detailedStatus',
        ),
        migrations.CreateModel(
            name='SocketClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detailedStatus', models.JSONField(blank=True, null=True)),
                ('error_code', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='LSISsocket.socketclientconfig')),
            ],
        ),
    ]
