# Generated by Django 5.2 on 2025-10-22 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0008_socketclientconfig_memory_groups_and_more"),
        (
            "corecode",
            "0015_remove_calcvariable_group_remove_calcvariable_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CalcGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("size_byte", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ControlGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "size_byte",
                    models.PositiveIntegerField(
                        blank=True, help_text="그룹 크기 (바이트 단위)", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AlterField(
            model_name="socketclientconfig",
            name="calc_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="연결된 계산 그룹",
                related_name="lsissocket_calc_groups",
                to="LSISsocket.calcgroup",
            ),
        ),
        migrations.CreateModel(
            name="CalcVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(blank=True, max_length=20)),
                (
                    "use_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dew_point", "dew_point"),
                            ("condensation_risk", "condensation_risk"),
                            ("calculate_ECp", "calculate_ECp"),
                            ("calculate_AWC", "calculate_AWC"),
                            ("calculate_SWSI", "calculate_SWSI"),
                            (
                                "calculate_stress_time_ratio",
                                "calculate_stress_time_ratio",
                            ),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="함수 인자값을 순서대로 저장 (리스트)",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="['감시','제어','기록','경보'] 중 복수 선택",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agriseed_calc_variables_in_group",
                        to="LSISsocket.calcgroup",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agriseed_as_calc_variable",
                        to="corecode.dataname",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="socketclientconfig",
            name="control_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="연결된 제어 그룹",
                related_name="lsissocket_control_groups",
                to="LSISsocket.controlgroup",
            ),
        ),
        migrations.CreateModel(
            name="ControlValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=30, verbose_name="명령상태")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="업데이트 일시"),
                ),
                (
                    "command_name",
                    models.CharField(max_length=100, verbose_name="명령이름"),
                ),
                ("target", models.CharField(max_length=100, verbose_name="타겟")),
                (
                    "data_type",
                    models.CharField(max_length=30, verbose_name="데이터타입"),
                ),
                ("value", models.JSONField(verbose_name="명령값")),
                (
                    "control_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="제어 일시"
                    ),
                ),
                (
                    "env_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="제어환경데이터"
                    ),
                ),
                (
                    "response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="명령 Response"
                    ),
                ),
                (
                    "control_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agriseed_control_values",
                        to="corecode.user",
                        verbose_name="제어 사용자",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControlValueHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=30, verbose_name="명령상태")),
                (
                    "command_name",
                    models.CharField(max_length=100, verbose_name="명령이름"),
                ),
                ("target", models.CharField(max_length=100, verbose_name="타겟")),
                (
                    "data_type",
                    models.CharField(max_length=30, verbose_name="데이터타입"),
                ),
                ("value", models.JSONField(verbose_name="명령값")),
                (
                    "control_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="제어 일시"
                    ),
                ),
                (
                    "env_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="제어환경데이터"
                    ),
                ),
                (
                    "response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="명령 Response"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "control_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="LSISsocket.controlvalue",
                        verbose_name="제어값",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControlVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(blank=True, max_length=20)),
                (
                    "args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="함수 인자값을 순서대로 저장 (리스트)",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="['감시','제어','기록','경보'] 중 복수 선택",
                    ),
                ),
                (
                    "applied_logic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agriseed_applications",
                        to="corecode.controllogic",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agriseed_control_variables_in_group",
                        to="LSISsocket.controlgroup",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agriseed_as_control_variable",
                        to="corecode.dataname",
                    ),
                ),
            ],
        ),
    ]
