# Generated by Django 5.2 on 2025-05-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0009_remove_socketclientconfig_comm_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketclientstatus',
            name='values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
