# Generated by Django 5.2 on 2025-10-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0009_calcgroup_controlgroup_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socketclientstatus",
            name="values",
        ),
    ]
