# Generated by Django 5.2 on 2025-10-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0010_remove_socketclientstatus_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="address",
            field=models.FloatField(default=0),
        ),
    ]
