# Generated by Django 5.2 on 2025-10-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0011_alter_variable_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='offset',
            field=models.CharField(default='0', help_text='오프셋 값 (정수 또는 소수점 형태의 문자열)', max_length=20),
        ),
    ]
