# Generated by Django 5.2 on 2025-10-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0012_alter_variable_offset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calcgroup",
            name="size_byte",
        ),
    ]
