# Generated by Django 5.2 on 2025-10-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0013_remove_calcgroup_size_byte"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calcvariable",
            name="use_method",
        ),
    ]
