# Generated by Django 5.2 on 2025-10-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0014_remove_calcvariable_use_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calcgroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='calcgroup',
            name='name',
        ),
    ]
