# Generated by Django 5.2 on 2025-10-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0015_remove_calcgroup_description_remove_calcgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlgroup',
            name='size_byte',
        ),
        migrations.AddField(
            model_name='calcgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calcgroup',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
