# Generated by Django 5.2 on 2025-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0016_remove_controlgroup_size_byte_calcgroup_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcvariable',
            name='args',
            field=models.JSONField(blank=True, default=list, help_text='함수 인자값을 순서대로 저장 (리스트)', null=True),
        ),
        migrations.AlterField(
            model_name='calcvariable',
            name='attributes',
            field=models.JSONField(blank=True, default=list, help_text="['감시','제어','기록','경보'] 중 복수 선택", null=True),
        ),
    ]
