# Generated by Django 5.2 on 2025-10-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0017_alter_calcvariable_args_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcvariable',
            name='args',
            field=models.JSONField(blank=True, default=list, help_text='연산 변수 인자값을 순서대로 저장 (리스트)', null=True),
        ),
    ]
