# Generated by Django 5.2 on 2025-10-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0018_alter_calcvariable_args'),
        ('corecode', '0015_remove_calcvariable_group_remove_calcvariable_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlartGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlartVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(blank=True, max_length=20)),
                ('threshold', models.JSONField(blank=True, default=dict, help_text='알림 기준값/설정 (예: {"min":0, "max":100})')),
                ('args', models.JSONField(blank=True, default=list, help_text='알림 변수 인자값을 순서대로 저장 (리스트)', null=True)),
                ('attributes', models.JSONField(blank=True, default=list, help_text='변수 속성 리스트', null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agriseed_alart_variables_in_group', to='LSISsocket.alartgroup')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agriseed_as_alart_variable', to='corecode.dataname')),
            ],
        ),
    ]
