# Generated by Django 5.2 on 2025-10-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0020_calcvariable_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calcvariable',
            name='attributes',
        ),
    ]
