# Generated by Django 5.2 on 2025-10-26 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0021_remove_calcvariable_attributes'),
        ('corecode', '0015_remove_calcvariable_group_remove_calcvariable_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alartvariable',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lsissocket_alart_variables_in_group', to='LSISsocket.alartgroup'),
        ),
        migrations.AlterField(
            model_name='alartvariable',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsissocket_as_alart_variable', to='corecode.dataname'),
        ),
        migrations.AlterField(
            model_name='calcvariable',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lsissocket_calc_variables_in_group', to='LSISsocket.calcgroup'),
        ),
        migrations.AlterField(
            model_name='calcvariable',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsissocket_as_calc_variable', to='corecode.dataname'),
        ),
        migrations.AlterField(
            model_name='calcvariable',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lsissocket_as_calc_result', to='corecode.dataname'),
        ),
        migrations.AlterField(
            model_name='controlvalue',
            name='control_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lsissocket_control_values', to='corecode.user', verbose_name='제어 사용자'),
        ),
        migrations.AlterField(
            model_name='controlvariable',
            name='applied_logic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsissocket_applications', to='corecode.controllogic'),
        ),
        migrations.AlterField(
            model_name='controlvariable',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lsissocket_control_variables_in_group', to='LSISsocket.controlgroup'),
        ),
        migrations.AlterField(
            model_name='controlvariable',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsissocket_as_control_variable', to='corecode.dataname'),
        ),
    ]
