# Generated by Django 5.2 on 2025-10-27 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0023_alter_calcvariable_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlvariable",
            name="attributes",
        ),
        migrations.AddField(
            model_name="controlvariable",
            name="result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lsissocket_as_control_result",
                to="LSISsocket.variable",
            ),
        ),
    ]
