# Generated by Django 5.2 on 2025-10-27 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0024_remove_controlvariable_attributes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlvariable",
            name="name",
        ),
    ]
