# Generated by Django 5.2 on 2025-10-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0026_remove_alartvariable_attributes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="remark",
            field=models.TextField(blank=True, help_text="비고", null=True),
        ),
    ]
