# Generated by Django 5.2 on 2025-10-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0027_variable_remark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensornodeconfig",
            name="adapter",
        ),
        migrations.RemoveField(
            model_name="sensornodeconfig",
            name="gateway",
        ),
        migrations.DeleteModel(
            name="ControlNodeConfig",
        ),
        migrations.DeleteModel(
            name="SensorNodeConfig",
        ),
    ]
