# Generated by Django 5.2 on 2025-10-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0028_remove_sensornodeconfig_adapter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('write_mode', models.CharField(choices=[('periodic', '주기적 쓰기'), ('one_time', '1회만 쓰기'), ('on_change', '값변경시 쓰기')], default='periodic', help_text='그룹 차원의 기본 쓰기 모드', max_length=20)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, help_text='주기적 쓰기 시 주기(초). cron이 있으면 무시될 수 있음', null=True)),
                ('cron', models.JSONField(blank=True, help_text='선택: 주기 설정을 위한 cron 표현(JSON)', null=True)),
                ('start_at', models.DateTimeField(blank=True, help_text='쓰기를 시작할 시각(옵션)', null=True)),
                ('end_at', models.DateTimeField(blank=True, help_text='쓰기를 종료할 시각(옵션)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='소프트 삭제 여부')),
                ('variables', models.ManyToManyField(blank=True, help_text='설정 쓰기 대상 변수 목록', related_name='lsissocket_setup_groups', to='LSISsocket.variable')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
