# Generated by Django 5.2 on 2025-10-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0029_setupgroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setupgroup",
            name="interval_seconds",
        ),
        migrations.RemoveField(
            model_name="setupgroup",
            name="write_mode",
        ),
    ]
