# Generated by Django 5.2 on 2025-10-29 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0030_remove_setupgroup_interval_seconds_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlvalue",
            name="command_name",
        ),
        migrations.RemoveField(
            model_name="controlvalue",
            name="env_data",
        ),
        migrations.RemoveField(
            model_name="controlvalue",
            name="target",
        ),
        migrations.RemoveField(
            model_name="controlvaluehistory",
            name="command_name",
        ),
        migrations.RemoveField(
            model_name="controlvaluehistory",
            name="env_data",
        ),
        migrations.RemoveField(
            model_name="controlvaluehistory",
            name="target",
        ),
        migrations.AddField(
            model_name="controlvalue",
            name="config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="control_values",
                to="LSISsocket.socketclientconfig",
                verbose_name="타겟 클라이언트",
            ),
        ),
        migrations.AddField(
            model_name="controlvalue",
            name="variable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="control_values",
                to="LSISsocket.variable",
                verbose_name="제어 변수",
            ),
        ),
        migrations.AddField(
            model_name="controlvaluehistory",
            name="config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="control_value_histories",
                to="LSISsocket.socketclientconfig",
                verbose_name="타겟 클라이언트",
            ),
        ),
        migrations.AddField(
            model_name="controlvaluehistory",
            name="variable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="control_value_histories",
                to="LSISsocket.variable",
                verbose_name="제어 변수",
            ),
        ),
    ]
