# Generated by Django 5.2 on 2025-10-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0031_remove_controlvalue_command_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlvalue",
            name="response",
        ),
        migrations.RemoveField(
            model_name="controlvaluehistory",
            name="response",
        ),
        migrations.AlterField(
            model_name="controlvalue",
            name="data_type",
            field=models.CharField(max_length=10, verbose_name="데이터타입"),
        ),
        migrations.AlterField(
            model_name="controlvalue",
            name="status",
            field=models.CharField(max_length=10, verbose_name="명령상태"),
        ),
        migrations.AlterField(
            model_name="controlvaluehistory",
            name="data_type",
            field=models.CharField(max_length=10, verbose_name="데이터타입"),
        ),
        migrations.AlterField(
            model_name="controlvaluehistory",
            name="status",
            field=models.CharField(max_length=10, verbose_name="명령상태"),
        ),
    ]
