# Generated by Django 5.2 on 2025-10-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0032_remove_controlvalue_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="value",
            field=models.CharField(
                blank=True, help_text="최종 값 (문자열 형태)", max_length=100, null=True
            ),
        ),
    ]
