# Generated by Django 5.2 on 2025-10-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0033_variable_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="socketclientconfig",
            name="alert_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="연결된 AlartGroup(경보) 목록",
                related_name="lsissocket_alert_groups",
                to="LSISsocket.alartgroup",
            ),
        ),
        migrations.AddField(
            model_name="socketclientconfig",
            name="setup_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="연결된 SetupGroup(설정) 목록",
                related_name="lsissocket_setup_groups",
                to="LSISsocket.setupgroup",
            ),
        ),
    ]
