# Generated by Django 5.2 on 2025-10-31 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0034_socketclientconfig_alert_groups_and_more"),
        ("corecode", "0016_alter_dataname_attributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socketclientconfig",
            name="alert_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="연결된 AlertGroup(경보) 목록",
                related_name="lsissocket_alert_groups",
                to="LSISsocket.alartgroup",
            ),
        ),
        migrations.RenameModel(
            old_name="AlartGroup",
            new_name="AlertGroup",
        ),
        migrations.CreateModel(
            name="AlertVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(blank=True, max_length=20)),
                (
                    "args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="알림 변수 인자값을 순서대로 저장 (리스트)",
                        null=True,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lsissocket_alert_variables_in_group",
                        to="LSISsocket.alertgroup",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lsissocket_as_alert_variable",
                        to="corecode.dataname",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lsissocket_as_alert_result",
                        to="LSISsocket.variable",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AlartVariable",
        ),
    ]
