# Generated by Django 5.2 on 2025-05-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='corecode.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MemoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.PositiveIntegerField()),
                ('start_device', models.CharField(choices=[('D', 'D'), ('M', 'M'), ('R', 'R')], max_length=2)),
                ('start_address', models.PositiveIntegerField()),
                ('size_byte', models.PositiveIntegerField()),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='corecode.projectversion')),
            ],
            options={
                'ordering': ['group_id'],
                'unique_together': {('project_version', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=2)),
                ('address', models.FloatField()),
                ('data_type', models.CharField(choices=[('bool', 'bool'), ('sint', 'sint'), ('usint', 'usint'), ('int', 'int'), ('uint', 'uint'), ('dint', 'dint'), ('udint', 'udint'), ('float', 'float')], max_length=10)),
                ('unit', models.CharField(choices=[('bit', 'bit'), ('byte', 'byte'), ('word', 'word'), ('dword', 'dword')], max_length=10)),
                ('scale', models.FloatField(default=1)),
                ('offset', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='corecode.memorygroup')),
            ],
        ),
    ]
