# Generated by Django 5.2 on 2025-07-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlvaluehistory',
            name='control_value',
        ),
    ]
