# Generated by Django 5.2 on 2025-05-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygroup',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
