# Generated by Django 5.2 on 2025-07-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0002_remove_controlvaluehistory_control_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlvaluehistory',
            name='control_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='corecode.controlvalue', verbose_name='제어값'),
        ),
    ]
