# Generated by Django 5.2 on 2025-05-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0002_memorygroup_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectversion',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='projectversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
