# Generated by Django 5.2 on 2025-07-10 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0003_controlvaluehistory_control_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('group_id', models.CharField(help_text='그룹 고유 ID (예: GRP_JEJU_EAST)', max_length=50, primary_key=True, serialize=False)),
                ('group_name', models.TextField(help_text='그룹명 (예: 제주 동부 지역)')),
                ('description', models.TextField(blank=True, help_text='그룹 설명 (선택 사항)', null=True)),
                ('timezone', models.CharField(help_text='시간대 (예: Asia/Seoul)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Group',
                'verbose_name_plural': 'Location Groups',
                'db_table': 'location_group',
            },
        ),
        migrations.CreateModel(
            name='LocationCode',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_type', models.CharField(help_text='코드 구분 (예: alarm_level, daytime_range)', max_length=50)),
                ('code_key', models.CharField(help_text='코드 키 값 (예: LEVEL_1, START_TIME)', max_length=50)),
                ('code_value', models.TextField(help_text='값 (예: 30, "06:00", JSON 형식도 가능)')),
                ('unit', models.CharField(help_text='단위 (예: ℃, %, HH:MM 등)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='코드 설명 (예: "주의 경고 상한온도")', null=True)),
                ('sort_order', models.IntegerField(default=0, help_text='정렬 순서')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='group_id', help_text='FK → location_group.group_id', on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='corecode.locationgroup')),
            ],
            options={
                'verbose_name': 'Location Code',
                'verbose_name_plural': 'Location Codes',
                'db_table': 'location_code',
            },
        ),
    ]
