# Generated by Django 5.2 on 2025-05-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0003_alter_projectversion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='attributes',
            field=models.JSONField(blank=True, default=list, help_text="['감시','제어','기록','경보'] 중 복수 선택"),
        ),
    ]
