# Generated by Django 5.2 on 2025-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_locationgroup_locationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='offset',
            field=models.FloatField(default=0),
        ),
    ]
