# Generated by Django 5.2 on 2025-07-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_alter_variable_offset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationcode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='locationgroup',
            options={},
        ),
        migrations.AlterModelTable(
            name='locationcode',
            table=None,
        ),
        migrations.AlterModelTable(
            name='locationgroup',
            table=None,
        ),
    ]
