# Generated by Django 5.2 on 2025-08-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0006_alter_locationcode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='사용자 프로필 이미지', null=True, upload_to='profile_images/'),
        ),
    ]
