# Generated by Django 5.2 on 2025-08-28 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0007_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlvalue',
            name='control_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_values', to='corecode.user', verbose_name='제어 사용자'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='corecode.user'),
        ),
    ]
