# Generated by Django 5.2 on 2025-05-12 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0007_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='Variable',
            field=models.JSONField(blank=True, default=dict, help_text="변수 정보(예: {'temperature': {'unit': 'C', 'scale': 1, 'offset': 0}})"),
        ),
        migrations.AddField(
            model_name='device',
            name='connetor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name_english',
            field=models.CharField(blank=True, help_text='Standardized device name (English)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name_korean',
            field=models.CharField(blank=True, help_text='단체표준 장비명(국문)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.CharField(blank=True, help_text='장비 단위', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='corecode.devicecompany'),
        ),
    ]
