# Generated by Django 5.2 on 2025-05-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0008_devicecompany_device_variable_device_connetor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='메뉴얼 제목', max_length=200)),
                ('file', models.FileField(help_text='사용자 취급 메뉴얼 파일', upload_to='user_manuals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='device',
            old_name='connetor',
            new_name='connector',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='Variable',
            new_name='variables',
        ),
        migrations.AddField(
            model_name='device',
            name='catalog',
            field=models.FileField(blank=True, help_text='장비 카탈로그 파일', null=True, upload_to='device_catalogs/'),
        ),
        migrations.AddField(
            model_name='device',
            name='user_manuals',
            field=models.ManyToManyField(blank=True, help_text='사용자 취급 메뉴얼 파일들', related_name='devices', to='corecode.usermanual'),
        ),
    ]
