# Generated by Django 5.2 on 2025-09-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0009_module_deviceinstance_and_more'),
    ]

    operations = [
        # 중간 단계(UniqueTogether/RemoveField)는 SQLite에서 인덱스 충돌을 유발할 수 있어 제거
        migrations.AlterModelOptions(
            name='projectversion',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Project Snapshot', 'verbose_name_plural': 'Project Snapshots'},
        ),
        migrations.DeleteModel(
            name='ControlVariable',
        ),
        migrations.DeleteModel(
            name='DeviceInstance',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
