# Generated by Django 5.2 on 2025-05-12 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0009_usermanual_rename_connetor_device_connector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='unit',
        ),
    ]
