# Generated by Django 5.2 on 2025-05-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0010_remove_device_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
