# Generated by Django 5.2 on 2025-09-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0010_alter_deviceinstance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='어댑터 이름', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='설명', null=True)),
                ('protocol', models.CharField(help_text='프로토콜 종류 (예: TCP, MQTT, HTTP 등)', max_length=50)),
                ('config', models.JSONField(blank=True, help_text='어댑터별 추가 설정값', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
            ],
        ),
    ]
