# Generated by Django 5.2 on 2025-09-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0045_alter_controlgroup_options_and_more'),
        ('corecode', '0011_adapter'),
    ]

    operations = [
        # 순서 변경: unique_together 해제 후 필드 제거
        migrations.AlterUniqueTogether(
            name='projectversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectversion',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='calcgroup',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='controlgroup',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='memorygroup',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='calcgroup',
            old_name='group_id',
            new_name='size_byte',
        ),
        migrations.RenameField(
            model_name='controlgroup',
            old_name='group_id',
            new_name='size_byte',
        ),
        migrations.AlterUniqueTogether(
            name='calcgroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='controlgroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='memorygroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='memorygroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='calcgroup',
            name='project_version',
        ),
        migrations.RemoveField(
            model_name='controlgroup',
            name='project_version',
        ),
        migrations.RemoveField(
            model_name='memorygroup',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='memorygroup',
            name='project_version',
        ),
        migrations.RemoveField(
            model_name='memorygroup',
            name='start_address',
        ),
        migrations.RemoveField(
            model_name='memorygroup',
            name='start_device',
        ),
        migrations.DeleteModel(
            name='ProjectVersion',
        ),
    ]
