# Generated by Django 5.2 on 2025-05-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0011_dataname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='dtype',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='dataname',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
