# Generated by Django 5.2 on 2025-09-28 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0012_remove_projectversion_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygroup',
            name='Device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_groups', to='corecode.device'),
        ),
    ]
