# Generated by Django 5.2 on 2025-05-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0012_dataname_dtype_alter_dataname_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user_manuals',
            field=models.ManyToManyField(blank=True, help_text='사용자 취급 메뉴얼 파일들', null=True, related_name='devices', to='corecode.usermanual'),
        ),
    ]
