# Generated by Django 5.2 on 2025-09-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0013_memorygroup_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygroup',
            name='Adapter',
            field=models.ForeignKey(blank=True, help_text='이 그룹이 속한 어댑터', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_groups', to='corecode.adapter'),
        ),
    ]
