# Generated by Django 5.2 on 2025-05-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0013_alter_device_user_manuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='variables',
            field=models.JSONField(blank=True, default={}, help_text="변수 정보(예: {'temperature': {'unit': 'C', 'scale': 1, 'offset': 0}})"),
        ),
    ]
