# Generated by Django 5.2 on 2025-09-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0053_calcgroup_alter_deviceinstance_memory_groups_and_more'),
        ('corecode', '0014_memorygroup_adapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calcvariable',
            name='group',
        ),
        migrations.RemoveField(
            model_name='calcvariable',
            name='name',
        ),
        migrations.DeleteModel(
            name='ControlGroup',
        ),
        migrations.RemoveField(
            model_name='controlvalue',
            name='control_user',
        ),
        migrations.RemoveField(
            model_name='controlvaluehistory',
            name='control_value',
        ),
        migrations.RemoveField(
            model_name='locationcode',
            name='group',
        ),
        migrations.RemoveField(
            model_name='memorygroup',
            name='Adapter',
        ),
        migrations.RemoveField(
            model_name='memorygroup',
            name='Device',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='group',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='name',
        ),
        migrations.DeleteModel(
            name='CalcGroup',
        ),
        migrations.DeleteModel(
            name='CalcVariable',
        ),
        migrations.DeleteModel(
            name='ControlValue',
        ),
        migrations.DeleteModel(
            name='ControlValueHistory',
        ),
        migrations.DeleteModel(
            name='LocationCode',
        ),
        migrations.DeleteModel(
            name='LocationGroup',
        ),
        migrations.DeleteModel(
            name='MemoryGroup',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
