# Generated by Django 5.2 on 2025-05-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0014_alter_device_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='attributes',
            field=models.CharField(blank=True, choices=[('status', 'Status'), ('upper', 'Upper'), ('lower', 'Lower'), ('reference', 'Reference'), ('difference', 'Difference')], max_length=20, null=True),
        ),
    ]
