# Generated by Django 5.2 on 2025-05-12 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0015_dataname_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_names', to='corecode.dataname'),
        ),
    ]
