# Generated by Django 5.2 on 2025-10-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "corecode",
            "0015_remove_calcvariable_group_remove_calcvariable_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataname",
            name="attributes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("status", "상태"),
                    ("upper", "상한"),
                    ("lower", "하한"),
                    ("reference", "제어"),
                    ("difference", "편차"),
                    ("calculation", "연산"),
                    ("command", "명령"),
                    ("info", "정보"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
