# Generated by Django 5.2 on 2025-05-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0016_alter_variable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connector',
            field=models.CharField(blank=True, choices=[('sensor', 'Sensor'), ('actuator', 'Actuator'), ('controller', 'Controller'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
