# Generated by Django 5.2 on 2025-05-12 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0017_alter_device_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='corecode.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='connector',
            field=models.CharField(blank=True, choices=[('LSIS-socket', 'LSIS-socket')], max_length=50, null=True),
        ),
    ]
