# Generated by Django 5.2 on 2025-05-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0018_project_device_alter_device_connector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='variables',
        ),
    ]
