# Generated by Django 5.2 on 2025-05-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0019_remove_device_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='alert_icon',
            field=models.ImageField(blank=True, null=True, upload_to='device_icons/alert/'),
        ),
    ]
