# Generated by Django 5.2 on 2025-05-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0020_device_alert_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='ctype',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
