# Generated by Django 5.2 on 2025-05-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0021_dataname_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='use_method',
            field=models.CharField(blank=True, choices=[('dew_point', 'dew_point'), ('condensation_risk', 'condensation_risk')], max_length=40, null=True),
        ),
    ]
