# Generated by Django 5.2 on 2025-05-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0022_dataname_use_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataname',
            name='attributes',
            field=models.CharField(blank=True, choices=[('status', 'Status'), ('upper', 'Upper'), ('lower', 'Lower'), ('reference', 'Reference'), ('difference', 'Difference'), ('calculation', 'Calculation'), ('command', 'Command')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dataname',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dataname',
            name='use_method',
            field=models.CharField(blank=True, choices=[], max_length=40, null=True),
        ),
    ]
