# Generated by Django 5.2 on 2025-05-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0022_dataname_use_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataname',
            name='use_method',
            field=models.CharField(blank=True, choices=[('dew_point', 'dew_point'), ('condensation_risk', 'condensation_risk'), ('calculate_ECp', 'calculate_ECp'), ('calculate_AWC', 'calculate_AWC'), ('calculate_SWSI', 'calculate_SWSI'), ('calculate_stress_time_ratio', 'calculate_stress_time_ratio'), ('ecp_risk_action', 'ecp_risk_action'), ('awc_risk_action', 'awc_risk_action')], max_length=40, null=True),
        ),
    ]
