# Generated by Django 5.2 on 2025-05-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0023_alter_dataname_use_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataname',
            name='use_method',
            field=models.CharField(blank=True, choices=[], max_length=40, null=True),
        ),
    ]
