# Generated by Django 5.2 on 2025-05-16 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0023_alter_dataname_attributes_alter_dataname_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='명령상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 일시')),
                ('command_name', models.CharField(max_length=100, verbose_name='명령이름')),
                ('target', models.CharField(max_length=100, verbose_name='타겟')),
                ('data_type', models.CharField(max_length=30, verbose_name='데이터타입')),
                ('value', models.JSONField(verbose_name='명령값')),
                ('control_at', models.DateTimeField(blank=True, null=True, verbose_name='제어 일시')),
                ('env_data', models.JSONField(blank=True, null=True, verbose_name='제어환경데이터')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='명령 Response')),
                ('control_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_values', to=settings.AUTH_USER_MODEL, verbose_name='제어 사용자')),
            ],
        ),
        migrations.CreateModel(
            name='ControlValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='명령상태')),
                ('command_name', models.CharField(max_length=100, verbose_name='명령이름')),
                ('target', models.CharField(max_length=100, verbose_name='타겟')),
                ('data_type', models.CharField(max_length=30, verbose_name='데이터타입')),
                ('value', models.JSONField(verbose_name='명령값')),
                ('control_at', models.DateTimeField(blank=True, null=True, verbose_name='제어 일시')),
                ('env_data', models.JSONField(blank=True, null=True, verbose_name='제어환경데이터')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='명령 Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('control_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='corecode.controlvalue', verbose_name='제어값')),
            ],
        ),
    ]
