# Generated by Django 5.2 on 2025-05-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0024_alter_dataname_use_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataname',
            name='attributes',
            field=models.CharField(blank=True, choices=[('status', 'Status'), ('upper', 'Upper'), ('lower', 'Lower'), ('reference', 'Reference'), ('difference', 'Difference'), ('calculation', 'Calculation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dataname',
            name='unit',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
