# Generated by Django 5.2 on 2025-05-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0024_controlvalue_controlvaluehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='method_args',
            field=models.JSONField(blank=True, default=list, help_text='계산 메서드에 필요한 인자들'),
        ),
        migrations.AddField(
            model_name='dataname',
            name='method_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
