# Generated by Django 5.2 on 2025-05-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0025_alter_dataname_attributes_alter_dataname_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataname',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
