# Generated by Django 5.2 on 2025-05-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0025_dataname_method_args_dataname_method_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='method_args_desc',
            field=models.JSONField(blank=True, default=dict, help_text='계산 메서드 인자 설명'),
        ),
        migrations.AlterField(
            model_name='dataname',
            name='use_method',
            field=models.CharField(blank=True, choices=[('dew_point', 'dew_point'), ('condensation_risk', 'condensation_risk'), ('calculate_ECp', 'calculate_ECp'), ('calculate_AWC', 'calculate_AWC'), ('calculate_SWSI', 'calculate_SWSI'), ('calculate_stress_time_ratio', 'calculate_stress_time_ratio')], max_length=40, null=True),
        ),
    ]
