# Generated by Django 5.2 on 2025-05-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0026_dataname_method_args_desc_alter_dataname_use_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataname',
            name='method_args_desc',
        ),
    ]
