# Generated by Django 5.2 on 2025-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0027_remove_dataname_method_args_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataname',
            name='method_args',
            field=models.JSONField(blank=True, default=dict, help_text='계산 메서드에 필요한 인자들'),
        ),
    ]
