# Generated by Django 5.2 on 2025-05-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0028_alter_dataname_method_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='method_args_desc',
            field=models.JSONField(blank=True, default=dict, help_text='계산 메서드 인자 설명'),
        ),
        migrations.AlterField(
            model_name='dataname',
            name='method_args',
            field=models.JSONField(blank=True, default=list, help_text='계산 메서드에 필요한 인자들'),
        ),
    ]
