# Generated by Django 5.2 on 2025-05-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0030_remove_dataname_method_args_dataname_method_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataname',
            name='method_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
