# Generated by Django 5.2 on 2025-05-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0031_alter_dataname_method_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataname',
            name='method_args_desc',
            field=models.JSONField(blank=True, default=dict, help_text='계산 메서드 인자 설명', null=True),
        ),
        migrations.AlterField(
            model_name='dataname',
            name='method_result',
            field=models.JSONField(blank=True, default=dict, help_text='계산 메서드 인자 설명', null=True),
        ),
    ]
