# Generated by Django 5.2 on 2025-05-23 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0032_alter_dataname_method_args_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('args', models.JSONField(blank=True, default=list, help_text='함수 인자값을 순서대로 저장 (리스트)')),
                ('return_from', models.CharField(blank=True, help_text='이 변수가 어떤 함수의 return 값인지 함수명 저장', max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_variables', to='corecode.dataname')),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_variables', to='corecode.projectversion')),
            ],
        ),
    ]
