# Generated by Django 5.2 on 2025-05-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0033_calcvariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calcvariable',
            name='project_version',
        ),
        migrations.AddField(
            model_name='calcvariable',
            name='device',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='CalcGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_groups', to='corecode.projectversion')),
            ],
            options={
                'ordering': ['group_id'],
                'unique_together': {('project_version', 'group_id')},
            },
        ),
        migrations.AddField(
            model_name='calcvariable',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='corecode.calcgroup'),
        ),
    ]
