# Generated by Django 5.2 on 2025-05-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0034_remove_calcvariable_project_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calcvariable',
            name='device',
        ),
    ]
