# Generated by Django 5.2 on 2025-05-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0035_remove_calcvariable_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcvariable',
            name='use_method',
            field=models.CharField(blank=True, choices=[('dew_point', 'dew_point'), ('condensation_risk', 'condensation_risk'), ('calculate_ECp', 'calculate_ECp'), ('calculate_AWC', 'calculate_AWC'), ('calculate_SWSI', 'calculate_SWSI'), ('calculate_stress_time_ratio', 'calculate_stress_time_ratio')], max_length=40, null=True),
        ),
    ]
