# Generated by Django 5.2 on 2025-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0036_calcvariable_use_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='method_args_type',
            field=models.JSONField(blank=True, default=dict, help_text='계산 메서드 인자 타입', null=True),
        ),
        migrations.AddField(
            model_name='dataname',
            name='method_result_type',
            field=models.CharField(blank=True, help_text='계산 메서드 반환 타입', max_length=100, null=True),
        ),
    ]
