# Generated by Django 5.2 on 2025-05-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0037_dataname_method_args_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calcvariable',
            old_name='unit',
            new_name='data_type',
        ),
        migrations.RemoveField(
            model_name='calcvariable',
            name='description',
        ),
        migrations.AddField(
            model_name='calcvariable',
            name='attributes',
            field=models.JSONField(blank=True, default=list, help_text="['감시','제어','기록','경보'] 중 복수 선택"),
        ),
    ]
