# Generated by Django 5.2 on 2025-05-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0038_rename_unit_calcvariable_data_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calcvariable',
            name='return_from',
        ),
    ]
