# Generated by Django 5.2 on 2025-06-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0040_alter_dataname_use_method_controlgroup_controllogic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllogic',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='controllogic',
            name='group',
        ),
        migrations.AlterField(
            model_name='controllogic',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dataname',
            name='use_method',
            field=models.CharField(blank=True, choices=[('dew_point', 'dew_point'), ('condensation_risk', 'condensation_risk'), ('calculate_ECp', 'calculate_ECp'), ('calculate_AWC', 'calculate_AWC'), ('calculate_SWSI', 'calculate_SWSI'), ('calculate_stress_time_ratio', 'calculate_stress_time_ratio')], max_length=40, null=True),
        ),
    ]
