# Generated by Django 5.2 on 2025-06-02 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0041_remove_controllogic_data_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllogic',
            name='args',
        ),
        migrations.RemoveField(
            model_name='controllogic',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='dataname',
            name='method_args_desc',
        ),
        migrations.RemoveField(
            model_name='dataname',
            name='method_args_type',
        ),
        migrations.RemoveField(
            model_name='dataname',
            name='method_description',
        ),
        migrations.RemoveField(
            model_name='dataname',
            name='method_result',
        ),
        migrations.RemoveField(
            model_name='dataname',
            name='method_result_type',
        ),
        migrations.RemoveField(
            model_name='dataname',
            name='use_method',
        ),
        migrations.AddField(
            model_name='controllogic',
            name='method_args_desc',
            field=models.JSONField(blank=True, default=dict, help_text='메서드 인자 설명', null=True),
        ),
        migrations.AddField(
            model_name='controllogic',
            name='method_args_type',
            field=models.JSONField(blank=True, default=dict, help_text='메서드 인자 타입', null=True),
        ),
        migrations.AddField(
            model_name='controllogic',
            name='method_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='controllogic',
            name='method_result',
            field=models.JSONField(blank=True, default=dict, help_text='메서드 결과 설명', null=True),
        ),
        migrations.AddField(
            model_name='controllogic',
            name='method_result_type',
            field=models.CharField(blank=True, help_text='메서드 반환 타입', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calcvariable',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_variables_in_group', to='corecode.calcgroup'),
        ),
        migrations.AlterField(
            model_name='calcvariable',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_calc_variable', to='corecode.dataname'),
        ),
        migrations.AlterField(
            model_name='controllogic',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dataname',
            name='attributes',
            field=models.CharField(blank=True, choices=[('status', 'Status'), ('upper', 'Upper'), ('lower', 'Lower'), ('reference', 'Reference'), ('difference', 'Difference'), ('calculation', 'Calculation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_variables', to='corecode.dataname'),
        ),
        migrations.CreateModel(
            name='ControlVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(blank=True, max_length=20)),
                ('args', models.JSONField(blank=True, default=list, help_text='함수 인자값을 순서대로 저장 (리스트)')),
                ('attributes', models.JSONField(blank=True, default=list, help_text="['감시','제어','기록','경보'] 중 복수 선택")),
                ('applied_logic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='corecode.controllogic')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_variables_in_group', to='corecode.controlgroup')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_control_variable', to='corecode.dataname')),
            ],
        ),
    ]
