# Generated by Django 5.2 on 2025-06-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0042_remove_controllogic_args_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllogic',
            name='name',
        ),
    ]
