# Generated by Django 5.2 on 2025-06-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0043_remove_controllogic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='method_args_desc',
            field=models.JSONField(blank=True, default=dict, help_text='계산 메서드 인자 설명', null=True),
        ),
        migrations.AddField(
            model_name='dataname',
            name='method_args_type',
            field=models.JSONField(blank=True, default=dict, help_text='계산 메서드 인자 타입', null=True),
        ),
        migrations.AddField(
            model_name='dataname',
            name='method_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dataname',
            name='method_result',
            field=models.JSONField(blank=True, default=dict, help_text='계산 메서드 인자 설명', null=True),
        ),
        migrations.AddField(
            model_name='dataname',
            name='method_result_type',
            field=models.CharField(blank=True, help_text='계산 메서드 반환 타입', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataname',
            name='use_method',
            field=models.CharField(blank=True, choices=[('dew_point', 'dew_point'), ('condensation_risk', 'condensation_risk'), ('calculate_ECp', 'calculate_ECp'), ('calculate_AWC', 'calculate_AWC'), ('calculate_SWSI', 'calculate_SWSI'), ('calculate_stress_time_ratio', 'calculate_stress_time_ratio'), ('hysteresis_control', 'hysteresis_control'), ('pid_control', 'pid_control'), ('proportional_control', 'proportional_control'), ('conditional_control', 'conditional_control'), ('schedule_based_control', 'schedule_based_control'), ('sensor_feedback_control', 'sensor_feedback_control'), ('ai_ml_based_control', 'ai_ml_based_control'), ('set_deviation_control', 'set_deviation_control'), ('set_threshold_control', 'set_threshold_control'), ('set_simple_conditional_control', 'set_simple_conditional_control'), ('set_time_based_control', 'set_time_based_control'), ('set_cycle_control', 'set_cycle_control'), ('set_on_off_timer_control', 'set_on_off_timer_control')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dataname',
            name='attributes',
            field=models.CharField(blank=True, choices=[('status', 'Status'), ('upper', 'Upper'), ('lower', 'Lower'), ('reference', 'Reference'), ('difference', 'Difference'), ('calculation', 'Calculation'), ('command', 'Command')], max_length=20, null=True),
        ),
    ]
