# Generated by Django 5.2 on 2025-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0044_dataname_method_args_desc_dataname_method_args_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllogic',
            name='description',
            field=models.TextField(blank=True, help_text='제어 로직 설명', null=True),
        ),
        migrations.AddField(
            model_name='controllogic',
            name='name',
            field=models.CharField(blank=True, help_text='제어 로직 이름', max_length=100, null=True),
        ),
    ]
