# Generated by Django 5.2 on 2025-06-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0045_controllogic_description_controllogic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllogic',
            name='description',
        ),
    ]
