# Generated by Django 5.2 on 2025-07-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0046_remove_controllogic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user_manuals',
            field=models.ManyToManyField(blank=True, help_text='사용자 취급 메뉴얼 파일들', related_name='devices', to='corecode.usermanual'),
        ),
    ]
