# Generated by Django 5.2 on 2025-07-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0047_alter_device_user_manuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='icon',
            field=models.CharField(blank=True, help_text='아이콘 클래스 (문자열)', max_length=100, null=True),
        ),
    ]
