# Generated by Django 5.2.7 on 2025-10-05 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTControllerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='통합제어기 이름', max_length=100)),
                ('serial', models.CharField(help_text='예: 4653500D004C003C (HEX 문자열, 바이트 단위로 저장됩니다)', max_length=256, validators=[django.core.validators.RegexValidator(message='16진수 문자열만 허용합니다.', regex='^[0-9A-Fa-f]+$')])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='위도 (예: 37.123456)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='경도 (예: 127.123456)', max_digits=9, null=True)),
                ('installation_address', models.TextField(blank=True, help_text='설치 주소', null=True)),
                ('rs485_channel', models.PositiveIntegerField(blank=True, help_text='RS-485 주 채널 번호 (옵션)', null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '통합제어기 설정',
                'verbose_name_plural': '통합제어기 설정',
            },
        ),
        migrations.CreateModel(
            name='MCUNodeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='노드 이름', max_length=100)),
                ('node_type', models.CharField(choices=[('sensor', 'Sensor'), ('control', 'Control')], default='sensor', max_length=10)),
                ('serial', models.CharField(help_text='예: 4653500D004C003C (HEX 문자열, 바이트 단위로 저장됩니다)', max_length=256, validators=[django.core.validators.RegexValidator(message='16진수 문자열만 허용합니다.', regex='^[0-9A-Fa-f]+$')])),
                ('rs485_address', models.PositiveIntegerField(blank=True, help_text='RS-485 주소 (옵션)', null=True)),
                ('rs485_channel', models.PositiveIntegerField(blank=True, help_text='RS-485 채널 번호 (옵션)', null=True)),
                ('baudrate', models.PositiveIntegerField(default=19200, help_text='통신 속도 (예: 9600)')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(blank=True, help_text='소속 통합제어기 (옵션)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='MCUnode.iotcontrollerconfig')),
            ],
            options={
                'verbose_name': 'MCU 노드 설정',
                'verbose_name_plural': 'MCU 노드 설정',
            },
        ),
    ]
