# Generated by Django 5.2.7 on 2025-10-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCUnode', '0002_remove_iotcontrollerconfig_rs485_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcunodeconfig',
            name='rs485_address',
        ),
    ]
