# Generated by Django 5.2 on 2025-07-08 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agriseed', '0001_initial'),
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlitem',
            name='item_name',
            field=models.ForeignKey(blank=True, help_text='제어 항목명(DataName)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_items', to='corecode.dataname'),
        ),
        migrations.AddField(
            model_name='controlhistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_histories', to='agriseed.device'),
        ),
        migrations.AddField(
            model_name='activity',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='agriseed.device'),
        ),
        migrations.AddField(
            model_name='controlsettings',
            name='facility',
            field=models.ForeignKey(blank=True, default='0', help_text='소속된 시설', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_settings', to='agriseed.facility'),
        ),
        migrations.AddField(
            model_name='recipeitemvalue',
            name='control_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_values', to='agriseed.controlitem'),
        ),
        migrations.AddField(
            model_name='recipeitemvalue',
            name='control_logic',
            field=models.ForeignKey(blank=True, help_text='적용할 제어 로직', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_item_values', to='corecode.controllogic'),
        ),
        migrations.AddField(
            model_name='recipeitemvalue',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_values', to='agriseed.recipeprofile'),
        ),
        migrations.AddField(
            model_name='variety',
            name='crop',
            field=models.ForeignKey(help_text='작물 종류', on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='agriseed.crop'),
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='variety',
            field=models.ForeignKey(blank=True, help_text='레시피 대상 품종', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_profiles', to='agriseed.variety'),
        ),
        migrations.AddField(
            model_name='varietyguide',
            name='variety',
            field=models.ForeignKey(help_text='연결된 품종', on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='agriseed.variety'),
        ),
        migrations.AddField(
            model_name='varietyimage',
            name='variety',
            field=models.ForeignKey(help_text='연결된 품종', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agriseed.variety'),
        ),
        migrations.AddField(
            model_name='zone',
            name='crop',
            field=models.ForeignKey(blank=True, help_text='작물 종류', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriseed.crop'),
        ),
        migrations.AddField(
            model_name='zone',
            name='facility',
            field=models.ForeignKey(help_text='소속된 시설', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='agriseed.facility'),
        ),
        migrations.AddField(
            model_name='zone',
            name='variety',
            field=models.ForeignKey(blank=True, help_text='품종', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriseed.variety'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='zone',
            field=models.ForeignKey(help_text='소속된 구역', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='agriseed.zone'),
        ),
        migrations.AddField(
            model_name='facilityhistory',
            name='zone',
            field=models.ForeignKey(help_text='소속된 구역', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='agriseed.zone'),
        ),
    ]
