# Generated by Django 5.2 on 2025-04-27 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='작물 종류명', max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='controlsettings',
            name='zone',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlhistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlrole',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlsettings',
            name='abnormal_humidity_alert',
            field=models.BooleanField(default=True, help_text='이상습도 알림 (기본값: 켜짐)'),
        ),
        migrations.AddField(
            model_name='controlsettings',
            name='abnormal_temp_alert',
            field=models.BooleanField(default=True, help_text='이상온도 알림 (기본값: 켜짐)'),
        ),
        migrations.AddField(
            model_name='controlsettings',
            name='facility',
            field=models.ForeignKey(blank=True, default='0', help_text='소속된 시설', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_settings', to='agriseed.facility'),
        ),
        migrations.AddField(
            model_name='controlsettings',
            name='fault_alert',
            field=models.BooleanField(default=True, help_text='고장알림 (기본값: 켜짐)'),
        ),
        migrations.AddField(
            model_name='controlsettings',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlsettings',
            name='water_alert',
            field=models.BooleanField(default=True, help_text='급수알림 (기본값: 켜짐)'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facilityhistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resolvedissue',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='environment_status',
            field=models.CharField(blank=True, default='정상', help_text='환경 상태 (예: 정상, 주의, 위험 등)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='expected_harvest_date',
            field=models.DateField(blank=True, help_text='예상 수확일', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='expected_yield',
            field=models.FloatField(blank=True, default=0.0, help_text='예상 수확량(kg)', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='health_status',
            field=models.CharField(blank=True, default='양호', help_text='건강 상태 (예: 양호, 주의, 위험 등)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='sowing_date',
            field=models.DateField(blank=True, help_text='파종일', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='status',
            field=models.CharField(blank=True, choices=[('활성화', '활성화'), ('비활성화', '비활성화'), ('작업중', '작업중')], default='활성화', help_text='구역 상태 (활성화, 비활성화, 작업중)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='style',
            field=models.CharField(blank=True, default='일반', help_text='구역 스타일 (예: 일반, 특수 등)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='crop',
            field=models.ForeignKey(blank=True, help_text='작물 종류', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriseed.crop'),
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='품종명', max_length=100)),
                ('category', models.CharField(blank=True, help_text='작물 분류 (예: 과채류)', max_length=100, null=True)),
                ('origin', models.CharField(blank=True, help_text='원산지', max_length=100, null=True)),
                ('registered_at', models.DateField(blank=True, help_text='등록일', null=True)),
                ('seed_amount', models.CharField(blank=True, help_text='씨앗 보유량', max_length=50, null=True)),
                ('difficulty', models.CharField(blank=True, help_text='재배 난이도', max_length=50, null=True)),
                ('temperature', models.JSONField(blank=True, help_text='적정 온도 범위', null=True)),
                ('humidity', models.JSONField(blank=True, help_text='적정 습도 범위', null=True)),
                ('sunlight', models.JSONField(blank=True, help_text='일조량 범위', null=True)),
                ('soil', models.JSONField(blank=True, help_text='토양 조건', null=True)),
                ('sowing_period', models.CharField(blank=True, help_text='파종기 범위', max_length=100, null=True)),
                ('harvest_period', models.CharField(blank=True, help_text='수확기 범위', max_length=100, null=True)),
                ('growth_duration', models.JSONField(blank=True, help_text='생육 기간 범위', null=True)),
                ('expected_yield', models.JSONField(blank=True, help_text='예상 수확량 범위', null=True)),
                ('fruit_size', models.JSONField(blank=True, help_text='과실 크기 범위', null=True)),
                ('sugar_content', models.JSONField(blank=True, help_text='당도 범위', null=True)),
                ('disease_resistance', models.CharField(blank=True, help_text='병해충 저항성', max_length=100, null=True)),
                ('note', models.CharField(blank=True, help_text='특이사항', max_length=200, null=True)),
                ('guide', models.TextField(blank=True, help_text='재배 가이드', null=True)),
                ('crop', models.ForeignKey(help_text='작물 종류', on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='agriseed.crop')),
            ],
        ),
        migrations.AddField(
            model_name='zone',
            name='variety',
            field=models.ForeignKey(blank=True, help_text='품종', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriseed.variety'),
        ),
        migrations.CreateModel(
            name='VarietyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.TextField(help_text='재배 가이드')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('author', models.CharField(blank=True, help_text='작성자', max_length=100, null=True)),
                ('note', models.CharField(blank=True, help_text='비고/특이사항', max_length=200, null=True)),
                ('stage_tips', models.JSONField(blank=True, help_text='재배 단계별 설정값 및 팁', null=True)),
                ('variety', models.ForeignKey(help_text='연결된 품종', on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='agriseed.variety')),
            ],
        ),
        migrations.CreateModel(
            name='VarietyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='품종 이미지', upload_to='variety_images/')),
                ('description', models.CharField(blank=True, help_text='이미지 설명', max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='업로드 일시')),
                ('variety', models.ForeignKey(help_text='연결된 품종', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agriseed.variety')),
            ],
        ),
    ]
