# Generated by Django 5.2 on 2025-04-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0002_crop_remove_controlsettings_zone_activity_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='controlhistory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='controlrole',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='controlsettings',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='facilityhistory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='resolvedissue',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
    ]
