# Generated by Django 5.2 on 2025-07-11 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsettings',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='소속된 시설', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_settings', to='agriseed.facility'),
        ),
    ]
