# Generated by Django 5.2 on 2025-07-11 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0003_alter_controlsettings_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='agriseed.device'),
        ),
        migrations.AlterField(
            model_name='controlhistory',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_histories', to='agriseed.device'),
        ),
    ]
