# Generated by Django 5.2 on 2025-04-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0003_alter_activity_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='daily_watering_count',
            field=models.IntegerField(default=1, help_text='일일 급수 횟수'),
        ),
        migrations.AddField(
            model_name='zone',
            name='watering_amount',
            field=models.FloatField(default=0.0, help_text='공급량 (mL)'),
        ),
        migrations.AddField(
            model_name='zone',
            name='watering_amount_per_time',
            field=models.FloatField(default=0.0, help_text='1회 급수량 (L)'),
        ),
        migrations.AddField(
            model_name='zone',
            name='watering_interval',
            field=models.CharField(default='매일', help_text='공급 주기 (예: 매일, 격일 등)', max_length=50),
        ),
    ]
