# Generated by Django 5.2 on 2025-08-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0004_alter_activity_device_alter_controlhistory_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='단계 이름 (예: 준비, 성장, 수확)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='단계 순서 지정용 정수')),
                ('duration_days', models.IntegerField(blank=True, help_text='이 단계의 기간 (일)', null=True)),
                ('description', models.TextField(blank=True, help_text='단계 설명')),
                ('recipe_profile', models.ForeignKey(help_text='레시피 프로필에 속한 단계', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agriseed.recipeprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
