# Generated by Django 5.2 on 2025-05-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0004_zone_daily_watering_count_zone_watering_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='LSIS',
            field=models.JSONField(blank=True, help_text='토양 조건', null=True),
        ),
    ]
