# Generated by Django 5.2 on 2025-05-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0005_facility_lsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='device',
            name='firmware',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_data',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
