# Generated by Django 5.2 on 2025-08-20 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0005_recipephase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='생성자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipe_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='수정자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_recipe_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipeprofile',
            name='name',
            field=models.CharField(help_text='레시피 이름', max_length=200),
        ),
    ]
