# Generated by Django 5.2 on 2025-07-02 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0006_remove_device_battery_remove_device_firmware_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='제어 항목명 (예: 온도, 습도, CO₂, EC, pH 등)', max_length=100)),
                ('unit', models.CharField(help_text='단위 (예: ℃, %, ppm)', max_length=50)),
                ('item_type', models.CharField(help_text='구분 (예: 센서, 액츄에이터, 목표값, 경계값 등)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='설명')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(help_text='레시피 이름 (예: 초기 생장기, 생식기 등)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_profiles', to='agriseed.crop')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItemValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_value', models.FloatField(help_text='설정값 (목표값 등)')),
                ('min_value', models.FloatField(blank=True, help_text='최소 허용값 (선택)', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='최대 허용값 (선택)', null=True)),
                ('control_mode', models.CharField(help_text='제어 방식 (예: 자동, 수동)', max_length=50)),
                ('priority', models.IntegerField(blank=True, help_text='우선순위 (선택)', null=True)),
                ('control_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_values', to='agriseed.controlitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_values', to='agriseed.recipeprofile')),
            ],
        ),
    ]
