# Generated by Django 5.2 on 2025-08-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0006_recipeprofile_created_by_recipeprofile_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipePhase',
            new_name='RecipeStep',
        ),
    ]
