# Generated by Django 5.2 on 2025-08-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0007_rename_recipephase_recipestep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitemvalue',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_values', to='agriseed.recipestep'),
        ),
    ]
