# Generated by Django 5.2 on 2025-07-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0007_controlitem_recipeprofile_recipeitemvalue'),
        ('corecode', '0046_remove_controllogic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlitem',
            name='item_name',
            field=models.ForeignKey(help_text='제어 항목명(DataName)', on_delete=django.db.models.deletion.CASCADE, related_name='control_items', to='corecode.dataname'),
        ),
    ]
