# Generated by Django 5.2 on 2025-07-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0008_alter_controlitem_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='controlitem',
            name='unit',
        ),
    ]
