# Generated by Django 5.2 on 2025-08-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0008_alter_recipeitemvalue_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitemvalue',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_values', to='agriseed.recipestep'),
        ),
    ]
