# Generated by Django 5.2 on 2025-08-26 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0009_alter_recipeitemvalue_recipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='코멘트 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='부모 코멘트', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='agriseed.recipecomment')),
                ('recipe', models.ForeignKey(help_text='레시피에 대한 코멘트', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='agriseed.recipeprofile')),
                ('user', models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_amount', models.FloatField(help_text='수확량 (kg)')),
                ('success', models.BooleanField(help_text='성공 여부')),
                ('notes', models.TextField(blank=True, help_text='추가 메모', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(help_text='레시피 시도 결과', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='agriseed.recipeprofile')),
                ('user', models.ForeignKey(help_text='시행자', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_performances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='도움됨(True)/도움안됨(False)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(help_text='코멘트에 대한 투표', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='agriseed.recipecomment')),
                ('user', models.ForeignKey(help_text='투표한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='별점 (1~5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(help_text='레시피에 대한 별점', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='agriseed.recipeprofile')),
                ('user', models.ForeignKey(help_text='평가자', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recipe', 'user')},
            },
        ),
    ]
