# Generated by Django 5.2 on 2025-07-02 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0009_remove_controlitem_item_type_remove_controlitem_unit'),
        ('corecode', '0046_remove_controllogic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitemvalue',
            name='control_mode',
        ),
        migrations.AddField(
            model_name='recipeitemvalue',
            name='control_logic',
            field=models.ForeignKey(blank=True, help_text='적용할 제어 로직', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_item_values', to='corecode.controllogic'),
        ),
    ]
