# Generated by Django 5.2 on 2025-07-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0010_remove_recipeitemvalue_control_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeprofile',
            name='description',
            field=models.TextField(blank=True, help_text='설명'),
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='기간 (일)', null=True),
        ),
    ]
