# Generated by Django 5.2 on 2025-08-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0010_recipecomment_recipeperformance_recipecommentvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='label_icon',
            field=models.CharField(blank=True, help_text='단계 아이콘 (선택 사항)', max_length=20, null=True),
        ),
    ]
