# Generated by Django 5.2 on 2025-08-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0011_recipestep_label_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='active',
            field=models.BooleanField(default=True, help_text='단계 활성화 여부'),
        ),
    ]
