# Generated by Django 5.2 on 2025-07-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0011_recipeprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeprofile',
            name='order',
            field=models.IntegerField(default=0, help_text='레시피 순서 (우선순위)'),
        ),
    ]
