# Generated by Django 5.2 on 2025-08-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0012_recipestep_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeprofile',
            name='bookmark',
            field=models.BooleanField(default=False, help_text='북마크 여부'),
        ),
    ]
