# Generated by Django 5.2 on 2025-07-06 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0012_recipeprofile_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeprofile',
            name='crop',
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='variety',
            field=models.ForeignKey(blank=True, help_text='레시피 대상 품종', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_profiles', to='agriseed.variety'),
        ),
    ]
