# Generated by Django 5.2 on 2025-07-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0013_remove_recipeprofile_crop_recipeprofile_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeprofile',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='레시피 활성화 여부', null=True),
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='삭제 여부', null=True),
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
