# Generated by Django 5.2 on 2025-08-29 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0013_recipeprofile_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitemvalue',
            name='control_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_values', to='agriseed.controlitem'),
        ),
    ]
