<<<<<<< HEAD
# Generated by Django 5.2 on 2025-09-02 14:32
=======
# Generated by Django 5.2 on 2025-09-03 07:09
>>>>>>> 9d532d28e88dfe506489439d9ef8c859c6dbc566

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0014_alter_recipeitemvalue_control_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tree_code', models.CharField(help_text='현장 표기 (예: B12-034)', max_length=20)),
                ('row_no', models.IntegerField(help_text='행 번호')),
                ('tree_no', models.IntegerField(help_text='주 번호')),
                ('notes', models.TextField(blank=True, help_text='특이사항', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tree_age', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.FloatField(help_text='Height in meters')),
                ('diameter', models.FloatField(help_text='Diameter in centimeters')),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('variety', models.ForeignKey(help_text='연결된 품종', on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='agriseed.variety')),
                ('zone', models.ForeignKey(help_text='소속된 구역', on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='agriseed.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Tree_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode_type', models.CharField(help_text='바코드 유형 (예: QR, Code128 등)', max_length=20)),
                ('barcode_value', models.CharField(help_text='바코드 값', max_length=100)),
                ('qr_payload', models.TextField(help_text='QR 코드 페이로드 (예: URL 또는 JSON)')),
                ('issue_date', models.DateField(help_text='발급일')),
                ('issued_by', models.CharField(help_text='발급자', max_length=100)),
                ('valid_from', models.DateField(help_text='유효 시작일')),
                ('valid_to', models.DateField(blank=True, help_text='유효 종료일 (빈 값이면 무한대로 간주)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='태그 활성화 여부')),
                ('notes', models.TextField(blank=True, help_text='특이사항', null=True)),
                ('tree', models.ForeignKey(help_text='소속된 나무', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='agriseed.tree')),
            ],
        ),
    ]
