# Generated by Django 5.2 on 2025-09-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0015_tree_tree_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='row_no',
            field=models.IntegerField(help_text='상단, 중단, 하단 구분'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='tree_no',
            field=models.IntegerField(help_text='나침반 각도'),
        ),
    ]
