# Generated by Django 5.2 on 2025-09-03 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0015_tree_tree_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_code', models.CharField(help_text='표본 코드(현장 식별자)', max_length=50, unique=True)),
                ('collected_at', models.DateTimeField(blank=True, help_text='채집 일시', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='위도(선택)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='경도(선택)', null=True)),
                ('sample_type', models.CharField(blank=True, help_text='표본 유형(예: 잎, 토양)', max_length=50, null=True)),
                ('measurements', models.JSONField(blank=True, help_text="측정값(JSON, 예: {'moisture': 12.3, 'ph': 6.5})", null=True)),
                ('attachments', models.JSONField(blank=True, help_text='첨부파일 경로 목록(JSON)', null=True)),
                ('notes', models.TextField(blank=True, help_text='비고/특이사항', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='기록 생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='기록 수정일시')),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('collected_by', models.ForeignKey(blank=True, help_text='채집자(사용자, 선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_specimens', to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(blank=True, help_text='관련 나무(선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens', to='agriseed.tree')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='나무 이미지', upload_to='tree_images/')),
                ('caption', models.CharField(blank=True, help_text='이미지 설명', max_length=200, null=True)),
                ('taken_at', models.DateTimeField(blank=True, help_text='촬영 일시', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='업로드 일시')),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('tree', models.ForeignKey(help_text='연결된 나무', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agriseed.tree')),
            ],
        ),
    ]
