# Generated by Django 5.2 on 2025-09-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0016_alter_tree_row_no_alter_tree_tree_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='tree_no',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='row_no',
            new_name='height_level',
        ),
    ]
