# Generated by Django 5.2 on 2025-09-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0016_specimendata_treeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='specimen_attachments/')),
                ('filename', models.CharField(blank=True, max_length=200, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_image', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments_files', to='agriseed.specimendata')),
            ],
        ),
    ]
