# Generated by Django 5.2 on 2025-09-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0017_specimenattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='height_level',
            field=models.CharField(blank=True, help_text='상단, 중단, 하단 구분', max_length=20, null=True),
        ),
    ]
