# Generated by Django 5.2 on 2025-09-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0017_rename_tree_no_tree_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='height_level',
            field=models.CharField(help_text='상단, 중단, 하단 구분'),
        ),
    ]
