# Generated by Django 5.2 on 2025-09-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0018_alter_tree_height_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='height_level',
        ),
        migrations.AddField(
            model_name='tree_tags',
            name='degree',
            field=models.IntegerField(blank=True, help_text='나침반 각도', null=True),
        ),
        migrations.AddField(
            model_name='tree_tags',
            name='height_level',
            field=models.CharField(blank=True, help_text='상단, 중단, 하단 구분', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tree_tags',
            name='issue_date',
            field=models.DateField(blank=True, help_text='발급일', null=True),
        ),
    ]
