# Generated by Django 5.2 on 2025-09-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0019_remove_tree_degree_remove_tree_height_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimendata',
            name='is_post_harvest',
            field=models.BooleanField(default=False, help_text='이 표본이 수확 후 시점에 채집되었는지 여부 (Tree_tags 기준으로 동기화)'),
        ),
        migrations.AddField(
            model_name='specimendata',
            name='is_pre_harvest',
            field=models.BooleanField(default=False, help_text='이 표본이 수확 전 시점에 채집되었는지 여부 (Tree_tags 기준으로 동기화)'),
        ),
        migrations.AddField(
            model_name='tree_tags',
            name='farm_log',
            field=models.TextField(blank=True, help_text='태그와 연결된 영농일지(간단 텍스트 저장)', null=True),
        ),
        migrations.AddField(
            model_name='tree_tags',
            name='has_farm_log',
            field=models.BooleanField(default=False, help_text='영농일지 작성 여부'),
        ),
        migrations.AddField(
            model_name='tree_tags',
            name='is_post_harvest',
            field=models.BooleanField(default=False, help_text='이 태그가 수확 후 기준인지 여부'),
        ),
        migrations.AddField(
            model_name='tree_tags',
            name='is_pre_harvest',
            field=models.BooleanField(default=False, help_text='이 태그가 수확 전 기준인지 여부'),
        ),
    ]
