# Generated by Django 5.2 on 2025-09-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0020_specimendata_is_post_harvest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimendata',
            name='is_pre_harvest',
        ),
        migrations.RemoveField(
            model_name='tree_tags',
            name='is_pre_harvest',
        ),
        migrations.AlterField(
            model_name='tree_tags',
            name='is_post_harvest',
            field=models.BooleanField(default=False, help_text='이 태그가 수확 후 기준인지 여부 (True=수확후, False=수확전)'),
        ),
    ]
