# Generated by Django 5.2 on 2025-09-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0021_remove_specimendata_is_pre_harvest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimendata',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='specimendata',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='specimendata',
            name='specimen_code',
        ),
    ]
