# Generated by Django 5.2 on 2025-09-06 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0022_remove_specimendata_latitude_and_more'),
        ('corecode', '0008_alter_controlvalue_control_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='설명')),
                ('item_name', models.ForeignKey(blank=True, help_text='측정 항목명(DataName)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_items', to='corecode.dataname')),
            ],
        ),
        migrations.CreateModel(
            name='SensorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='설명')),
                ('item_name', models.ForeignKey(blank=True, help_text='센서 항목명(DataName)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_items', to='corecode.dataname')),
            ],
        ),
    ]
