# Generated by Django 5.2 on 2025-09-07 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0023_measurementitem_sensoritem'),
        ('corecode', '0008_alter_controlvalue_control_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarietyDataThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_good', models.FloatField(blank=True, help_text='정상 최소값 (선택)', null=True)),
                ('max_good', models.FloatField(blank=True, help_text='정상 최대값 (선택)', null=True)),
                ('min_warn', models.FloatField(blank=True, help_text='경고 최소값 (선택)', null=True)),
                ('max_warn', models.FloatField(blank=True, help_text='경고 최대값 (선택)', null=True)),
                ('priority', models.IntegerField(default=0, help_text='우선순위 (높을수록 우선 적용)')),
                ('note', models.TextField(blank=True, help_text='설명/메모', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_name', models.ForeignKey(help_text='측정/센서 항목 (DataName)', on_delete=django.db.models.deletion.CASCADE, related_name='variety_thresholds', to='corecode.dataname')),
                ('variety', models.ForeignKey(help_text='대상 품종', on_delete=django.db.models.deletion.CASCADE, related_name='data_thresholds', to='agriseed.variety')),
            ],
            options={
                'ordering': ['-priority', 'variety', 'data_name'],
                'unique_together': {('variety', 'data_name')},
            },
        ),
        migrations.CreateModel(
            name='QualityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sensor', 'Sensor'), ('specimen', 'Specimen'), ('manual', 'Manual'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('level_name', models.CharField(choices=[('NORMAL', 'Normal'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('level_severity', models.IntegerField()),
                ('quality', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_events', to='corecode.dataname')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_events', to='agriseed.variety')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='agriseed.varietydatathreshold')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
