# Generated by Django 5.2 on 2025-09-07 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0024_varietydatathreshold_qualityevent'),
        ('corecode', '0008_alter_controlvalue_control_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='varietydatathreshold',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='varietydatathreshold',
            name='level_label',
            field=models.CharField(blank=True, help_text='레벨 라벨 (예: normal=정상, warning=주의, critical=부적합)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='varietydatathreshold',
            name='quality_label',
            field=models.CharField(blank=True, help_text='품질 라벨 (예: good=우수, fair=양호, poor=불량)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='varietydatathreshold',
            name='data_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variety_thresholds', to='corecode.dataname'),
        ),
        migrations.AlterField(
            model_name='varietydatathreshold',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='varietydatathreshold',
            name='max_good',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='varietydatathreshold',
            name='max_warn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='varietydatathreshold',
            name='min_good',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='varietydatathreshold',
            name='min_warn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='varietydatathreshold',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='varietydatathreshold',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='varietydatathreshold',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_thresholds', to='agriseed.variety'),
        ),
        migrations.AlterUniqueTogether(
            name='varietydatathreshold',
            unique_together={('variety', 'data_name', 'priority')},
        ),
    ]
