# Generated by Django 5.2 on 2025-09-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0025_alter_varietydatathreshold_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varietydatathreshold',
            name='max_high_risk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varietydatathreshold',
            name='max_risk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varietydatathreshold',
            name='min_high_risk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varietydatathreshold',
            name='min_risk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
