# Generated by Django 5.2 on 2025-09-09 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0026_varietydatathreshold_max_high_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='recipe_profile',
            field=models.ForeignKey(blank=True, help_text='적용된 레시피 프로필 (단일)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='agriseed.recipeprofile'),
        ),
    ]
