# Generated by Django 5.2 on 2025-09-09 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0026_varietydatathreshold_max_high_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='recipe_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='agriseed.recipeprofile'),
        ),
    ]
