# Generated by Django 5.2 on 2025-09-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0027_zone_recipe_profile'),
        ('agriseed', '0027_zone_recipeprofiles'),
    ]

    operations = [
    ]
