# Generated by Django 5.2 on 2025-09-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0028_merge_20250909_2136'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='zone',
                    name='daily_watering_count',
                ),
                migrations.RemoveField(
                    model_name='zone',
                    name='watering_amount',
                ),
                migrations.RemoveField(
                    model_name='zone',
                    name='watering_amount_per_time',
                ),
                migrations.RemoveField(
                    model_name='zone',
                    name='watering_interval',
                ),
            ],
        ),
        migrations.AddField(
            model_name='zone',
            name='seed_amount',
            field=models.FloatField(default=0.0, help_text='사용 종자량 (단위: g, 기본값: 0.0)'),
        ),
    ]
