# Generated by Django 5.2 on 2025-09-10 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0030_add_zone_recipe_profile_column_if_missing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('recurrence', models.JSONField(blank=True, help_text='예: {"freq":"DAILY","interval":1}', null=True)),
                ('reminders', models.JSONField(blank=True, help_text='예: [60, 10]  # 시작 60분 전, 10분 전', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('attendees', models.ManyToManyField(blank=True, related_name='events_attending', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='소속 시설', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='agriseed.facility')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=2, help_text='1=high,2=normal,3=low')),
                ('status', models.CharField(default='open', max_length=50)),
                ('reminders', models.JSONField(blank=True, help_text='예: [1440, 60] # 하루 전, 1시간 전', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='소속 시설', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to='agriseed.facility')),
                ('zone', models.ForeignKey(blank=True, help_text='관련 구역', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_items', to='agriseed.zone')),
            ],
            options={
                'ordering': ['completed', '-priority', 'due_date'],
            },
        ),
    ]
