# Generated by Django 5.2 on 2025-09-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0031_calendarevent_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(blank=True, help_text='종료 시간(선택 사항)', null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start',
            field=models.DateTimeField(help_text='시작 시간'),
        ),
    ]
