# Generated by Django 5.2 on 2025-09-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0032_alter_calendarevent_end_alter_calendarevent_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(),
        ),
    ]
