# Generated by Django 5.2 on 2025-09-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0033_alter_calendarevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(blank=True, help_text='종료 시간', null=True),
        ),
    ]
