# Generated by Django 5.2 on 2025-09-16 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0034_todoitem_updated_at_alter_calendarevent_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='location',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='관련 구역', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='agriseed.zone'),
        ),
    ]
