# Generated by Django 5.2 on 2025-09-16 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0035_remove_calendarevent_location_calendarevent_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('enabled', models.BooleanField()),
                ('expected_yield', models.FloatField(blank=True, default=0.0, help_text='예상 수확량(kg)', null=True)),
                ('sowing_date', models.DateField(blank=True, help_text='파종일', null=True)),
                ('expected_harvest_date', models.DateField(blank=True, help_text='예상 수확일', null=True)),
                ('seed_amount', models.FloatField(default=0.0, help_text='사용 종자량 (단위: g, 기본값: 0.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 여부')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_schedules', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='소속 시설', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_schedules', to='agriseed.facility')),
                ('recipe_profile', models.ForeignKey(blank=True, help_text='적용된 레시피 프로필 (단일)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='agriseed.recipeprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='expected_harvest_date',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='expected_yield',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='recipe_profile',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='seed_amount',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='sowing_date',
        ),
        migrations.AddField(
            model_name='zone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 시각', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정 시각', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='최종 수정자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_zones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarschedule',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='관련 구역', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_schedules', to='agriseed.zone'),
        ),
    ]
