# Generated by Django 5.2 on 2025-09-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0036_calendarschedule_delete_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarschedule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarschedule',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
