# Generated by Django 5.2 on 2025-09-16 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0037_calendarschedule_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='variety',
        ),
        migrations.AddField(
            model_name='calendarschedule',
            name='crop',
            field=models.ForeignKey(blank=True, help_text='작물 종류', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriseed.crop'),
        ),
        migrations.AddField(
            model_name='calendarschedule',
            name='variety',
            field=models.ForeignKey(blank=True, help_text='품종', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriseed.variety'),
        ),
    ]
