# Generated by Django 5.2 on 2025-09-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0038_remove_zone_crop_remove_zone_variety_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarschedule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='calendarschedule',
            name='title',
        ),
    ]
