# Generated by Django 5.2 on 2025-09-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0039_remove_calendarschedule_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlitem',
            name='scada_tag_name',
            field=models.TextField(blank=True, help_text='XSCADA 태그 이름', null=True),
        ),
    ]
