# Generated by Django 5.2 on 2025-09-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0040_controlitem_scada_tag_name'),
        ('corecode', '0009_module_deviceinstance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('group_id', models.CharField(help_text='그룹 고유 ID (예: GRP_JEJU_EAST)', max_length=50, primary_key=True, serialize=False)),
                ('group_name', models.TextField(help_text='그룹명 (예: 제주 동부 지역)')),
                ('description', models.TextField(blank=True, help_text='그룹 설명 (선택 사항)', null=True)),
                ('timezone', models.CharField(help_text='시간대 (예: Asia/Seoul)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recipeitemvalue',
            name='control_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agriseed_recipe_values', to='agriseed.controlitem'),
        ),
        migrations.CreateModel(
            name='CalcVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(blank=True, max_length=20)),
                ('use_method', models.CharField(blank=True, max_length=40, null=True)),
                ('args', models.JSONField(blank=True, default=list, help_text='함수 인자값을 순서대로 저장 (리스트)')),
                ('attributes', models.JSONField(blank=True, default=list, help_text="['감시','제어','기록','경보'] 중 복수 선택")),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agriseed_calc_variables_in_group', to='corecode.calcgroup')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agriseed_as_calc_variable', to='corecode.dataname')),
            ],
        ),
        migrations.CreateModel(
            name='ControlGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agriseed_control_groups', to='corecode.projectversion')),
            ],
            options={
                'ordering': ['group_id'],
                'unique_together': {('project_version', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='ControlVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(blank=True, max_length=20)),
                ('args', models.JSONField(blank=True, default=list, help_text='함수 인자값을 순서대로 저장 (리스트)')),
                ('attributes', models.JSONField(blank=True, default=list, help_text="['감시','제어','기록','경보'] 중 복수 선택")),
                ('applied_logic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agriseed_applications', to='corecode.controllogic')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agriseed_control_variables_in_group', to='agriseed.controlgroup')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agriseed_as_control_variable', to='corecode.dataname')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='모듈 이름 (예: 관수 모듈 A)', max_length=120)),
                ('module_type', models.CharField(choices=[('irrigation', 'Irrigation'), ('env_control', 'Environment Control'), ('lighting', 'Lighting'), ('sensor_hub', 'Sensor Hub'), ('fertigation', 'Fertigation'), ('storage', 'Storage'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, help_text='모듈 설명', null=True)),
                ('control_scope', models.JSONField(blank=True, default=dict, help_text='이 모듈이 제어/감시하는 범위(구역/노드 등)')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='운영 기본 설정 (JSON)')),
                ('order', models.PositiveIntegerField(default=0, help_text='모듈 정렬 순서')),
                ('is_enabled', models.BooleanField(default=True, help_text='모듈 활성화 여부')),
                ('status', models.CharField(default='idle', help_text='운영 상태 (예: idle, running, maintenance)', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, help_text='소속 시설(Facility)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agriseed_modules', to='agriseed.facility')),
                ('location_group', models.ForeignKey(blank=True, help_text='지역 그룹 연결 (선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='agriseed.locationgroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='인스턴스별 표시명 (선택)', max_length=150, null=True)),
                ('serial_number', models.CharField(help_text='시리얼 번호/고유 식별자', max_length=200)),
                ('hw_version', models.CharField(blank=True, max_length=50, null=True)),
                ('fw_version', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(blank=True, help_text='네트워크/관리용 장치 ID (MAC, UUID 등)', max_length=200, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('maintenance', 'Maintenance'), ('unknown', 'Unknown')], default='unknown', help_text='장비 상태', max_length=30)),
                ('last_seen', models.DateTimeField(blank=True, help_text='마지막 응답 시각', null=True)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='런타임 구성값 (JSON)')),
                ('health', models.JSONField(blank=True, default=dict, help_text='헬스/진단 정보 (JSON)')),
                ('location_within_module', models.CharField(blank=True, help_text='모듈 내 설치 위치(예: 구역A-포인트3)', max_length=200, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(blank=True, help_text='장비 카탈로그(Device) 참조', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agriseed_instances', to='corecode.device')),
                ('module', models.ForeignKey(blank=True, help_text='소속 모듈', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='agriseed.module')),
            ],
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['module_type'], name='agriseed_mo_module__016f95_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_enabled'], name='agriseed_mo_is_enab_e020bb_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinstance',
            index=models.Index(fields=['serial_number'], name='agriseed_de_serial__68fb69_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinstance',
            index=models.Index(fields=['status'], name='agriseed_de_status_749bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinstance',
            index=models.Index(fields=['last_seen'], name='agriseed_de_last_se_fc2abb_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceinstance',
            index=models.Index(fields=['catalog'], name='agriseed_de_catalog_364046_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceinstance',
            unique_together={('catalog', 'serial_number')},
        ),
    ]
