# Generated by Django 5.2 on 2025-09-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0041_locationgroup_alter_recipeitemvalue_control_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='단계 순서 지정용 정수'),
        ),
    ]
