# Generated by Django 5.2 on 2025-09-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0041_locationgroup_alter_recipeitemvalue_control_item_and_more'),
        ('corecode', '0009_module_deviceinstance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='location_group',
            field=models.ForeignKey(blank=True, help_text='지역 그룹 연결 (선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agriseed_modules', to='corecode.locationgroup'),
        ),
        migrations.DeleteModel(
            name='LocationGroup',
        ),
    ]
