# Generated by Django 5.2 on 2025-09-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0042_controlitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlitem',
            options={'ordering': ['order']},
        ),
    ]
