# Generated by Django 5.2 on 2025-09-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0042_alter_module_location_group_delete_locationgroup'),
        ('agriseed', '0043_alter_controlitem_options'),
    ]

    operations = [
    ]
