# Generated by Django 5.2 on 2025-09-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0044_merge_20250926_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlgroup',
            options={'ordering': ['group_id', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='controlgroup',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='controlgroup',
            name='group_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='controlgroup',
            name='project_version',
        ),
    ]
