# Generated by Django 5.2 on 2025-09-28 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0045_alter_controlgroup_options_and_more'),
        ('corecode', '0014_memorygroup_adapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceinstance',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='deviceinstance',
            name='agriseed_de_catalog_364046_idx',
        ),
        migrations.AlterUniqueTogether(
            name='deviceinstance',
            unique_together=set(),
        ),
        # 1) 충돌 방지: FK 추가 전에 기존 device_id(CharField)를 먼저 제거
        migrations.RemoveField(
            model_name='deviceinstance',
            name='device_id',
        ),
        # 2) 그 외 legacy 필드 제거 (순서 무관)
        migrations.RemoveField(
            model_name='deviceinstance',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='deviceinstance',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='deviceinstance',
            name='fw_version',
        ),
        migrations.RemoveField(
            model_name='deviceinstance',
            name='health',
        ),
        migrations.RemoveField(
            model_name='deviceinstance',
            name='hw_version',
        ),
        migrations.RemoveField(
            model_name='deviceinstance',
            name='mac_address',
        ),
        # 3) 신규 필드 추가
        migrations.AddField(
            model_name='deviceinstance',
            name='adapter',
            field=models.ForeignKey(blank=True, help_text='연결된 어댑터', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agriseed_device_instances', to='corecode.adapter'),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='device',
            field=models.ForeignKey(blank=True, help_text='연결된 코어 디바이스', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agriseed_device_instances', to='corecode.device'),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='facility',
            field=models.ForeignKey(blank=True, editable=False, help_text='모듈 기반 시설(자동 동기화)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_instances', to='agriseed.facility'),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='memory_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 메모리 그룹', related_name='device_instances', to='corecode.memorygroup'),
        ),
        # 4) 기존 필드 속성 변경
        migrations.AlterField(
            model_name='deviceinstance',
            name='install_date',
            field=models.DateField(blank=True, help_text='설치 일자', null=True),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='활성 여부'),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='serial_number',
            field=models.CharField(help_text='장치 고유 시리얼 번호', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='status',
            field=models.CharField(default='idle', help_text='상태 (예: idle, active, fault)', max_length=30),
        ),
    ]
