# Generated by Django 5.2 on 2025-09-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0046_alter_deviceinstance_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='module',
            name='agriseed_mo_module__016f95_idx',
        ),
        migrations.RemoveField(
            model_name='module',
            name='control_scope',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='module',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='module',
            name='status',
        ),
    ]
