# Generated by Django 5.2 on 2025-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0047_remove_module_agriseed_mo_module__016f95_idx_and_more'),
        ('corecode', '0014_memorygroup_adapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstance',
            name='calc_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 계산 그룹', related_name='device_instances', to='corecode.calcgroup'),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='control_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 제어 그룹', related_name='device_instances', to='agriseed.controlgroup'),
        ),
    ]
