# Generated by Django 5.2 on 2025-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0048_deviceinstance_calc_groups_and_more'),
        ('corecode', '0014_memorygroup_adapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinstance',
            name='calc_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 계산 그룹', null=True, related_name='device_instances', to='corecode.calcgroup'),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='control_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 제어 그룹', null=True, related_name='device_instances', to='agriseed.controlgroup'),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='memory_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 메모리 그룹', null=True, related_name='device_instances', to='corecode.memorygroup'),
        ),
    ]
