# Generated by Django 5.2 on 2025-09-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0050_alter_deviceinstance_calc_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinstance',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='LSIS',
        ),
        migrations.RemoveField(
            model_name='module',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='module',
            name='location_group',
        ),
        migrations.AddField(
            model_name='facility',
            name='module',
            field=models.ManyToManyField(blank=True, help_text='연결된 모듈', related_name='facilities', to='agriseed.module'),
        ),
    ]
