# Generated by Django 5.2 on 2025-09-30 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0051_remove_deviceinstance_facility_remove_facility_lsis_and_more'),
        ('corecode', '0014_memorygroup_adapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('group_id', models.CharField(help_text='그룹 고유 ID (예: GRP_JEJU_EAST)', max_length=50, primary_key=True, serialize=False)),
                ('group_name', models.TextField(help_text='그룹명 (예: 제주 동부 지역)')),
                ('description', models.TextField(blank=True, help_text='그룹 설명 (선택 사항)', null=True)),
                ('timezone', models.CharField(help_text='시간대 (예: Asia/Seoul)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='controlgroup',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='controlgroup',
            name='group_id',
        ),
        migrations.AddField(
            model_name='controlgroup',
            name='size_byte',
            field=models.PositiveIntegerField(blank=True, help_text='그룹 크기 (바이트 단위)', null=True),
        ),
        migrations.AlterField(
            model_name='calcvariable',
            name='use_method',
            field=models.CharField(blank=True, choices=[('dew_point', 'dew_point'), ('condensation_risk', 'condensation_risk'), ('calculate_ECp', 'calculate_ECp'), ('calculate_AWC', 'calculate_AWC'), ('calculate_SWSI', 'calculate_SWSI'), ('calculate_stress_time_ratio', 'calculate_stress_time_ratio')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='ControlValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='명령상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 일시')),
                ('command_name', models.CharField(max_length=100, verbose_name='명령이름')),
                ('target', models.CharField(max_length=100, verbose_name='타겟')),
                ('data_type', models.CharField(max_length=30, verbose_name='데이터타입')),
                ('value', models.JSONField(verbose_name='명령값')),
                ('control_at', models.DateTimeField(blank=True, null=True, verbose_name='제어 일시')),
                ('env_data', models.JSONField(blank=True, null=True, verbose_name='제어환경데이터')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='명령 Response')),
                ('control_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agriseed_control_values', to='corecode.user', verbose_name='제어 사용자')),
            ],
        ),
        migrations.CreateModel(
            name='ControlValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='명령상태')),
                ('command_name', models.CharField(max_length=100, verbose_name='명령이름')),
                ('target', models.CharField(max_length=100, verbose_name='타겟')),
                ('data_type', models.CharField(max_length=30, verbose_name='데이터타입')),
                ('value', models.JSONField(verbose_name='명령값')),
                ('control_at', models.DateTimeField(blank=True, null=True, verbose_name='제어 일시')),
                ('env_data', models.JSONField(blank=True, null=True, verbose_name='제어환경데이터')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='명령 Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('control_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='agriseed.controlvalue', verbose_name='제어값')),
            ],
        ),
    ]
