# Generated by Django 5.2 on 2025-09-30 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0004_delete_memorygroup_memorygroup_variable'),
        ('agriseed', '0052_locationgroup_alter_controlgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('size_byte', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='memory_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 메모리 그룹', related_name='device_instances', to='LSISsocket.memorygroup'),
        ),
        migrations.AlterField(
            model_name='calcvariable',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agriseed_calc_variables_in_group', to='agriseed.calcgroup'),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='calc_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 계산 그룹', related_name='device_instances', to='agriseed.calcgroup'),
        ),
        migrations.CreateModel(
            name='LocationCode',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_type', models.CharField(help_text='코드 구분 (예: alarm_level, daytime_range)', max_length=50)),
                ('code_key', models.CharField(help_text='코드 키 값 (예: LEVEL_1, START_TIME)', max_length=50)),
                ('code_value', models.TextField(help_text='값 (예: 30, "06:00", JSON 형식도 가능)')),
                ('unit', models.CharField(help_text='단위 (예: ℃, %, HH:MM 등)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='코드 설명 (예: "주의 경고 상한온도")', null=True)),
                ('sort_order', models.IntegerField(default=0, help_text='정렬 순서')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='group_id', help_text='FK → location_group.group_id', on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='agriseed.locationgroup')),
            ],
        ),
    ]
