# Generated by Django 5.2 on 2025-10-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0053_calcgroup_alter_deviceinstance_memory_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='facilitys',
            field=models.ForeignKey(blank=True, help_text='소속된 시설', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='agriseed.facility'),
        ),
    ]
