# Generated by Django 5.2 on 2025-10-10 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSISsocket', '0006_memorygroup_start_address_and_more'),
        ('agriseed', '0054_module_facilitys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinstance',
            name='calc_groups',
        ),
        migrations.RemoveField(
            model_name='deviceinstance',
            name='control_groups',
        ),
        migrations.AddField(
            model_name='module',
            name='calc_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 계산 그룹', related_name='device_instances', to='agriseed.calcgroup'),
        ),
        migrations.AddField(
            model_name='module',
            name='control_groups',
            field=models.ManyToManyField(blank=True, help_text='연결된 제어 그룹', related_name='device_instances', to='agriseed.controlgroup'),
        ),
        migrations.RemoveField(
            model_name='deviceinstance',
            name='memory_groups',
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='serial_number',
            field=models.CharField(blank=True, help_text='장치 고유 시리얼 번호', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='memory_groups',
            field=models.ForeignKey(blank=True, help_text='연결된 메모리 그룹', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_instances', to='LSISsocket.memorygroup'),
        ),
    ]
