# Generated by Django 5.2 on 2025-10-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriseed', '0055_remove_deviceinstance_calc_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='calc_groups',
        ),
        migrations.RemoveField(
            model_name='module',
            name='control_groups',
        ),
    ]
