# Generated by Django 5.2 on 2025-10-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LSISsocket", "0009_calcgroup_controlgroup_and_more"),
        ("agriseed", "0056_remove_module_calc_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calcvariable",
            name="group",
        ),
        migrations.RemoveField(
            model_name="calcvariable",
            name="name",
        ),
        migrations.RemoveField(
            model_name="controlvariable",
            name="group",
        ),
        migrations.RemoveField(
            model_name="controlhistory",
            name="device",
        ),
        migrations.RemoveField(
            model_name="controlvalue",
            name="control_user",
        ),
        migrations.RemoveField(
            model_name="controlvaluehistory",
            name="control_value",
        ),
        migrations.RemoveField(
            model_name="controlvariable",
            name="applied_logic",
        ),
        migrations.RemoveField(
            model_name="controlvariable",
            name="name",
        ),
        migrations.DeleteModel(
            name="CalcGroup",
        ),
        migrations.DeleteModel(
            name="CalcVariable",
        ),
        migrations.DeleteModel(
            name="ControlGroup",
        ),
        migrations.DeleteModel(
            name="ControlHistory",
        ),
        migrations.DeleteModel(
            name="ControlValue",
        ),
        migrations.DeleteModel(
            name="ControlValueHistory",
        ),
        migrations.DeleteModel(
            name="ControlVariable",
        ),
    ]
